### ISSUE TITLE
The voice recording of has when the screen turns off and what was recording is erased

### ISSUE THREAD

**Issue by discapacidad5** [SchildiChat/schildichat-desktop#104]
Steps to reproduce
1. Where do you start? What can you see? When you stepped on the record button and slid it so that it stays recorded without having your finger on the screen, and starts recording a long message if the screen turns off the recording clears
 2. What do you click? I click on voice mic

Intended result and actual result

What did you expect? I was hoping I could record the entire voice memo and the screen won't turn off while I was recording I was hoping that just like when you send a voice message for another message or when I watch a video, the phone remains active while it is recording. #### What happened instead? The screen turned off during recording and the recording was completely erased Start recording again and the screen turned off again and the same thing happened again on the screen is set to turn off 30 seconds if the phone is not in use I think this could be fixed by sending a message to keep the screen on Keep the phone awake while recording this way This way the screen would not turn off even if it takes a long time to record There are applications like reading applications with video applications that keep the phone awake while it is playing. I don't know about programming but I understand that this is a command that is sent every so often to keep the phone active.

Your phone model
Samsung s9

Operating system version
Android 10.0

Application version and app store
Element versión 1.3.1 olm versión 3.2.4

Homeserver
Matrix.org

**Comment by su-ex** [comment]
Wrong repo? I assume you meant Android?!?

**Comment by discapacidad5** [comment]
> ¿Repo incorrecto? ¿¡¿Supongo que te refieres a Android?!?

If it's true, I'm sorry, I didn't realize that this is the desktop version.
