### ISSUE TITLE
Send button as alternative to enter key

### ISSUE THREAD

**Issue by SpiritCroc** [SchildiChat/schildichat-desktop#11]
One user requested a send button next to the message input field, which can be used instead of the enter button to send messages.
The use-case is likely when having the setting to use enter-button to create newlines (-> Settings/preferences/Use Ctrl + Enter to send a message - ~~element does not have this yet btw, it was picked from [here](https://github.com/matrix-org/matrix-react-sdk/pull/5160)~~), and not having to remember how to send messages in this case.
The icon is probably best taken from SchildiChat-Android, and we might want to make this a setting (off by default?) - or maybe show it only when ctrl+enter to send is enabled.

**Comment by su-ex** [comment]
Introduced upstream in v1.7.23
