### ISSUE TITLE
Find a way to support emoji from Signal, etc if possible

### ISSUE THREAD

**Issue by ilikenwf** [SchildiChat/schildichat-desktop#114]
This may be a server issue but I bridge Signal into Matrix, and whenever someone reacts to a message or posts an emoji from signal within their messages, all I see on both Android and Desktop are "??" indicating some missing unicode character, I assume.

**Comment by SpiritCroc** [comment]
That's a bridge issue. Whoever runs the bridge might want to set `LANG=en_US.UTF-8` or something similar for the environment where signald runs (e.g. when running it as systemd service, add `Environment=LANG=en_US.UTF-8` to the `[Service]` section) - at least that's what fixed it for me (server was running with `LANG=C` before I think, which doesn't like umlauts).
