### ISSUE TITLE
Reactions row missing on modern layout

### ISSUE THREAD

**Issue by unbeatable-101** [SchildiChat/schildichat-desktop#116]
[Screen Recording 2021-12-18 at 00.56.19.zip](https://github.com/SchildiChat/schildichat-desktop/files/7738826/Screen.Recording.2021-12-18.at.00.56.19.zip)
<img width="754" alt="Screen Shot 2021-12-18 at 00 56 14" src="https://user-images.githubusercontent.com/58151048/146631085-c196462a-7baf-49ef-ae67-f24abc60520e.png">

**Comment by su-ex** [comment]
This is a problem with the modern layout only.
I've already fixed it, will be in the next release.

**Comment by su-ex** [comment]
Fixed: https://github.com/SchildiChat/matrix-react-sdk/commit/82724e83d86cc5b2b1534fb269fef51f06b72233
