### ISSUE TITLE
Cannot Search in Encrypted Rooms in Schildichat Desktop (Windows 10) due to "missing components"

### ISSUE THREAD

**Issue by PaarthShah** [SchildiChat/schildichat-desktop#117]
```
SchildiChat version: 1.9.7-sc.1
Olm version: 3.2.8
```

Element Desktop, installed on the side, does not have this same problem, and encrypted messages can be searched as-expected.

Error:

> # Message search
> SchildiChat is missing some components required for securely caching encrypted messages locally. If you'd like to experiment with this feature, build a custom SchildiChat Desktop with search components added.

![image](https://user-images.githubusercontent.com/20485810/147158781-9fa13ae7-27a3-492f-9538-a4deedd395d4.png)
![image](https://user-images.githubusercontent.com/20485810/147158848-acbbfa97-fed5-4d8e-9a46-36a5a0092f50.png)

**Comment by PaarthShah** [comment]
I understand this has been brought up [before](https://matrix.to/#/!eSTlitQAfqxWWEHMFD:matrix.org/$AEmgTHjElqEP0uWp80yVfIO8G7wZKd03eIuq6AaN5dM?via=schildi.chat&via=matrix.org&via=envs.net), and I'm planning to investigate myself as well in my spare time, but I wanted to make an issue to track it/source ideas from anyone else who might be able to help.

**Comment by su-ex** [comment]
I've tried setting up a dev environment on Windows 10 and have documented it here: https://gist.github.com/su-ex/2a456e368f4abcda2c9c2e737a67d89d
Sadly it got stuck on missing `patch`, although it should have definitely been there.
Maybe you / somebody else has an idea how to get this working, I'm out of ideas.

If you're trying to replicate this, note that you need to change `yarn dist` to `yarn build` in the `web` block of the Makefile.

**Comment by Dalethium** [comment]
I can confirm this on windows 11 with the latest build. I also built the windows portable from source and it was still not working.

I would consider this a critical issue tbh.
```
SchildiChat version: 1.10.4-sc.1
Olm version: 3.2.8
Edition	Windows 11 Pro
Version	22H2
Installed on	‎2022-‎03-‎06
OS build	22567.100
Experience	Windows Feature Experience Pack 1000.22567.100.0
```

**Comment by Dalethium** [comment]
> I've tried setting up a dev environment on Windows 10 and have documented it here: https://gist.github.com/su-ex/2a456e368f4abcda2c9c2e737a67d89d Sadly it got stuck on missing `patch`, although it should have definitely been there. Maybe you / somebody else has an idea how to get this working, I'm out of ideas.
> 
> If you're trying to replicate this, note that you need to change `yarn dist` to `yarn build` in the `web` block of the Makefile.

I am not entirely certain what you mean by this, however, if you are looking to build this while on a windows machine I would recommend using the ubuntu WSL subsystem, installing the packages listed for the debian build along with installing wine32 (I installed wine64 too) by following this guide [here](https://vitux.com/how-to-install-wine-on-ubuntu/) along with [mono](https://www.mono-project.com/download/stable/#download-lin) and then just the zip package on apt-get to top it off. That's how I got it to build on a windows PC. I am not entirely sure all the steps I took but it should be similar to that. I did not really test the client thoroughly, just long enough to check if search worked.

**Comment by su-ex** [comment]
@Dalethium That's how I build for Windows currently. The problem with this approach is that search in encrypted rooms doesn't work this way. And this is what this issue is about. 😉

**Comment by abirhasan132** [comment]
#117

**Comment by SpiritCroc** [comment]
Should be addressed starting with https://github.com/SchildiChat/schildichat-desktop/releases/tag/v1.11.81-sc.0.test.0 .
