### ISSUE TITLE
Runs in background unexpectedly

### ISSUE THREAD

**Issue by vhscom** [SchildiChat/schildichat-desktop#121]
Installed from Flatpack. App is nice. But I continue to receive notifications in the background even after I stop it. That should not happen. And there's no clear way to prevent it other than logging out.

```
SchildiChat version: 1.9.8-sc.1
Olm version: 3.2.8
OS: Arch Linux
Desktop: GNOME
```

**Comment by su-ex** [comment]
This is a messaging app, so it is intended to run in the background to be able to receive messages.
You can quit via Ctrl+Q inside the app or through right clicking the tray icon.
