### ISSUE TITLE
Custom theme and Code blocks

### ISSUE THREAD

**Issue by TheTrveAnthony** [SchildiChat/schildichat-desktop#124]
Hi,

This is more a bug report than an issue.

I use Schildichat (installed from aur) with a custom theme, and I noticed that codeblocks background color gets its value from `roomlist-background-color`, here is my `config.json` (generated by pywal), I modified `roomlist-background-color` to red so you can better see the problem

```json
{
    "showLabsSettings": true,

    "settingDefaults": {
        "custom_themes": [
        {
            "name": "Wal",
            "is_dark": true,
            "colors": {
              "accent-color": "#79cd99",
              "accent": "#79cd99",
              "primary-color": "#226047",
              "warning-color": "#134F33",
              "alert": "#134F33",
              "sidebar-color": "#0C6B37",
              "roomlist-background-color": "#ff0000",
              "roomlist-text-color": "#79cd99",
              "roomlist-text-secondary-color": "#0F131C",
              "roomlist-highlights-color": "#548f6b",
              "roomlist-separator-color": "#0F131C",
              "timeline-background-color": "#0F131C",
              "timeline-text-color": "#79cd99",
              "timeline-text-secondary-color": "#79cd99",
              "timeline-highlights-color": "#0F131C",
              "eventbubble-others-bg": "#28442E",
              "eventbubble-self-bg": "#0C6B37",
              "eventbubble-selected-bg": "#843821",
              "username-colors": ["#0F131C", "#134F33", "#28442E",
              "#0C6B37", "#226047", "#843821", "#04913A",
              "#79cd99"],
              "avatar-background-colors": ["#0C6B37", "#226047",
              "#843821"],
              "reaction-row-button-selected-bg-color": "#226047",
              "menu-selected-color": "#226047",
              "focus-bg-color": "#226047",
              "room-highlight-color": "#226047",
              "other-user-pill-bg-color": "#226047",
              "togglesw-off-color": "#226047",
              "secondary-content": "#79cd99",
              "tertiary-content": "#79cd99"
            }
        }
        ]
    }
}
```
and this is what I get:
![schildi](https://user-images.githubusercontent.com/40374762/152881800-441f1a3a-e4ee-48c3-ba6d-2da1f6745456.png)

Besides [this page](https://github.com/SchildiChat/element-web/blob/sc/docs/theming.md) which doesn't mention code blocks color, I haven't found any documentation about theming.

Would you know how to fix this ?

Thank you

EDIT : Syntax color is gone too

**Comment by su-ex** [comment]
Right, this should probably be exposed as its own variable: https://github.com/SchildiChat/matrix-react-sdk/blob/f75014957fa461d8aef9b5a9934f3bf2e606b45d/res/themes/light-custom/css/_custom.scss#L133

This file is also what you should refer to when building custom themes. Element has not updated the documentation for ages and SchildiChat has two own variables introduced.

About syntax color: Is it gone with the inbuilt light and dark theme as well or only custom themes? If it's only with custom themes, is this the same when using Element?

**Comment by su-ex** [comment]
Then the missing syntax color is upstream and should be fixed there.
