### ISSUE TITLE
[FR] Restore Window position and size

### ISSUE THREAD

**Issue by wuast94** [SchildiChat/schildichat-desktop#129]
Would be nice when SchildiChat would restore the Size and Position, at the moment it starts on my main screen and I always have to move it back to my pivot screen. 

I don't know why some Apps does restore it and some not but it isn't default in windows I think 😅

**Comment by su-ex** [comment]
That's probably more a job for your desktop environment or window manager than the application itself.

**Comment by wuast94** [comment]
My fault, I'm talking about the windows version, should mentioned that right?😜🙃

**Comment by su-ex** [comment]
Yeah, probably. xD
But it shouldn't matter. If I remember right, Windows 11 got features to arrange applications in a specific way for a specific screen configuration, that is restored, whenever the same screen configuration is detected. So still, this is nothing the application itself should do.

**Comment by wuast94** [comment]
It should work yes but under specific cases, would just love to see this working, windows is what it is.

**Comment by su-ex** [comment]
I have no clue about Windows, so it's nothing I can solve. I'm assigning "wontfix" because this is something I won't solve and "invalid" because it's not the applications job to do that imo. But if someone wants to investigate and suggest a solution, I won't stop that.
