### ISSUE TITLE
logs out of account after upgrading version

### ISSUE THREAD

**Issue by jahway603** [SchildiChat/schildichat-desktop#130]
The client logs me out of my account after upgrading the version installed. It's not clear if this is a feature or a bug.

**Comment by Kloenk** [comment]
On which platform/os?

**Comment by jahway603** [comment]
This is occurring on Arch Linux, specifically with the schildichat-desktop-bin AUR package. This issue has occurred in the past too, but since it had occurred again I've opened this issue. When I have to login again it creates a new "Matrix Session" which then needs to be verified again.

**Comment by jahway603** [comment]
Closing issue as the behaviour did not occur when upgrading to the latest version, https://github.com/SchildiChat/schildichat-desktop/releases/tag/v1.10.12-sc.1
