### ISSUE TITLE
Markdown quote format issue

### ISSUE THREAD

**Issue by Dalethium** [SchildiChat/schildichat-desktop#131]
SchildiChat version: 1.10.4-sc.1
Olm version: 3.2.8

In markdown on most apps, quotes require a space after the ``>`` in order to make a quote -- for example ``>[space]this is a quote`` should make a quote, but ``>.>`` should make a face. In this client ``>.>`` makes a quote of ``.>`` instead of providing the face. -- it's worth noting that ``\>.>`` works as intended for the face. -- this also adversely effects greentexts. This issue is also present on android. Let me know if I should forward this to element or if this is something to be fixed here!

**Comment by su-ex** [comment]
This is something which should be handled upstream by Element.

**Comment by Dalethium** [comment]
> This is something which should be handled upstream by Element.

Posted the issue as 21361 on element-web :)
