### ISSUE TITLE
Unsupported browser?

### ISSUE THREAD

**Issue by lgwapnitsky** [SchildiChat/schildichat-desktop#133]
I just downloaded the latest release, and I'm seeing "unsupported browser" whenever I go to the main page. I'm running the latest versions of chrome, brave, and firefox, and receive the error on all 3.

Advice is welcome.

**Comment by su-ex** [comment]
How does the same version of Element behave (the part before the `sc` in the SchildiChat version string)?
SchildiChat shouldn't deviate here from upstream.

**Comment by lgwapnitsky** [comment]
Just tried the latest version of element-web and didn't receive the message
on any browser

**Comment by su-ex** [comment]
That's very weird. Can you look at the devtools console? Maybe there's further information why it thinks the browser is not supported.
