### ISSUE TITLE
Image/Attachment doesn't appear

### ISSUE THREAD

**Issue by Uncover-monetize** [SchildiChat/schildichat-desktop#135]
Occasionally when switching to chat bubbles instead of modern any attachments/images disappear completely. Switching back temporarily seems to fix it for a while. 
Happened on Kubuntu

**Comment by su-ex** [comment]
Are you switching the layout often instead this setting being a one time change? How does it behave after starting the app after it has been fully closed? And does Element behave the same?
I can't reproduce this.

**Comment by Uncover-monetize** [comment]
> Are you switching the layout often instead this setting being a one time change? How does it behave after starting the app after it has been fully closed? And does Element behave the same? I can't reproduce this.

I switched it months ago and then left it alone, it just occurred out of the blue a few days ago. Hasn't happened since, never had the issue on element. Tried reopening it and no changes still works, I'm assuming it was some minor glitch on my device.

**Comment by su-ex** [comment]
Ok, let's wait and see. If this happens often, we can try to further debug this.

**Comment by Uncover-monetize** [comment]
Thank you!
