### ISSUE TITLE
Make "logout session" screen less user-error-prone

### ISSUE THREAD

**Issue by SpiritCroc** [SchildiChat/schildichat-desktop#142]
I keep logging out my current session when trying to remove other old sessions, because of the placement of the sign out buttons on the security settings page.

Possible solutions:

1. arrange the icons differently?
2. before logging out the current session, check if any other session is checkmarked, and in this case show an "are you sure" note if you still press the button to sign out the current session instead of the marked ones
3. just always show a "Are you sure to log out your current session" prompt

**Comment by su-ex** [comment]
Upstream is working on it, there's already the "New session manager" labs option.
