### ISSUE TITLE
Room with Disappearing messages shows notification - no message available

### ISSUE THREAD

**Issue by moan0s** [SchildiChat/schildichat-desktop#143]
Maybe this is a upstream bug, if so should i report this to element?

# Steps to reproduce

0. Use an account on a Synapse server that makes use of retention (purges messages)
1. Create a new room
2. Send an m.retention event with a small retention time (here one hour)
```
{
  "type": "m.room.retention",
  "sender": "@xy:example.com",
  "content": {
    "max_lifetime": 3600000
  },
  "state_key": "",
  "origin_server_ts": 1641353041750,
  "unsigned": {
    "age": 17572771043
  },
  "event_id": "$7wf6WmAsADF56w3gPx-TSzeikYbeA-7kro77rT7nE",
  "room_id": "!ABCDEyfgmxxaqWTULn:example.com"
}
```
3. Send some messages
4. Log out and log in after messages have been purged (depends on server configuration).

## What happens

Now you can see the room where you activated disappearing messages and see a notification (the small white dot). But the room itself is empty as all messages have been purged and there is no way to mark this room as read.

![image](https://user-images.githubusercontent.com/25753802/181206565-c47786b2-8f2a-44a7-bee9-5b714326cc6b.png)

## Expected result

Room looks like there never was a message.

**Comment by su-ex** [comment]
This is very likely upstream, there's nothing changed in this regard compared to Element. I didn't test this though, so probably you should test with Element as well before reporting to them.
