### ISSUE TITLE
– v1.11.3 merge introduced issues to fix before release

### ISSUE THREAD

**Issue by su-ex** [SchildiChat/schildichat-desktop#146]
- [x] read receipts in the bubble layout (https://github.com/SchildiChat/matrix-react-sdk/commit/2f80d27a45f7f2a757aeb01ba53c5dfc4b2b95fc)
- [x] red text for mentions (https://github.com/SchildiChat/matrix-react-sdk/commit/f32ceadaa9dd15f3162de34585e32ed1dfb0b53c)

**Comment by cloudrac3r** [comment]
- [ ] In the fullscreen ctrl-k room switcher, clicking on the room options `...` button does not open the menu (works upstream)
- [ ] Cannot mark rooms as unread. (it just does nothing, no console messages, no network requests)

**Comment by su-ex** [comment]
Obsolete.
