### ISSUE TITLE
AppImageUpdate

### ISSUE THREAD

**Issue by Thatoo** [SchildiChat/schildichat-desktop#150]
Would it be possible to include AppImageUpdate feature into the Schildichat AppImage : https://github.com/AppImageCommunity/AppImageUpdate ?

**Comment by Kloenk** [comment]
This is mainly designed for nightly updates, which we currently do not have. Furthermore this is a CPP library, designed to be used specifically with cmake. Both we are not using (apart from some libraries, which we don't build ourselves). So I don't See much advantage, but only a huge amount of work with this.
