### ISSUE TITLE
unecrypted shield appears in 1.11.8-sc.1 in encrypted room

### ISSUE THREAD

**Issue by waclaw66** [SchildiChat/schildichat-desktop#151]
![obrazek](https://user-images.githubusercontent.com/15554561/193138928-2975928e-ac9d-4156-948c-cd1de4341af0.png)

It's just a visual flaw, it dissapers when message is scrolled down (out of sight) and up again.
The same also with incomming messages, they have grey shield sometimes.

Element 1.11.8 works fine, no visual disturbances.

**Comment by blockomat2100** [comment]
Same for me, but the red shielded messages also disappear with the following error: `Can't load this message (m.room.message)` when I scroll in the room.

**Comment by n3niu** [comment]
Same here on Windows desktop version

**Comment by mal-tee** [comment]
Same here!

**Comment by su-ex** [comment]
Will be fixed with the next release: https://github.com/SchildiChat/matrix-react-sdk/commit/68f99488f590bb3623ee2bcf096a697e8d38505b
