### ISSUE TITLE
Can't load this message for own messages

### ISSUE THREAD

**Issue by mal-tee** [SchildiChat/schildichat-desktop#156]
Hi!

After writing messages, they often disappear and are replaced by an error message.

![image](https://user-images.githubusercontent.com/45886910/197734096-e00c029f-12b9-4247-aeef-9778022f9c44.png)

They seem to appear on the other side. I already tried "clear cache and reload".

This happens with a matrix.org account in an encrypted chat.
```
SchildiChat version: 1.11.8-sc.1
Olm version: 3.2.12
```
Thanks and please let me know if you need more information :D

**Comment by su-ex** [comment]
This is actually both the same issue, so maybe one could be closed. Whatever.
In the meantime until it's fixed, just re-enter the room (swap between two rooms or space and room) and the messages will reappear.

**Comment by mal-tee** [comment]
Thank you!

Closing in favour of #151
