### ISSUE TITLE
a small translation fix/

### ISSUE THREAD

**Issue by autoteelar** [SchildiChat/schildichat-desktop#157]
hi, this is just a small nitpick i noticed while using the program, when using combined lists, it shows Normal Priority in english even when using Japanese, on element for low priority uses 低優先度,  低 meaning low and 優先度 meaning degree of relative priority. for Normal priority i think something like this would be good 常優先度. 常 meaning the usual state of things, and 優先度 once again meaning degree of relative priority. imo this seems to be the most accurate translation. 

i would be grateful if you could add this, it just feels weird having one in japanese and one in english, my thanks :)

**Comment by autoteelar** [comment]
its just 1 line for 1 word my friend, the language already exists. should take 5 seconds for you to fix it.
do i need to send pictures as an example? 

![image](https://user-images.githubusercontent.com/76745649/197977108-196c5526-8bb4-4a2a-b70c-cdab5e9cc19d.png)
as you can see here its all in japanese besides "Normal Priority" 

i clicked the link you sent but i have no idea how to use it, and is it really necessary for something this small? that seems like its meant for entire translations. as i said this is just literally 1 word. you are the main schildichat developer you should know how to do this better than i do.

**Comment by autoteelar** [comment]
also why close this as "completed" when it hasn't even been worked on in the slightest? seems kind of dismissive to me

**Comment by SpiritCroc** [comment]
It's closed since translations are done over weblate by the community, and then get imported into this repository. We don't change them here.

**Comment by autoteelar** [comment]
accurate enough, is there anywhere i can submit this word to get changed somewhere? i clicked the url but its just really huge theres all kinds of stuff in there

**Comment by SpiritCroc** [comment]
Choose matrix-react-sdk (I admit this is not clear for first-time contributors), then there should be a string search

**Comment by autoteelar** [comment]
im better at debugging than i am at coding/infastructure, apologies there, i would mostly appreciate if this input was taken at least. as i dont know what else to do with it, it doesnt happen in element as the Normal Priority thing comes from schildichat i think

**Comment by autoteelar** [comment]
oh ok i see, thanks!

**Comment by autoteelar** [comment]
i dont happen to see 日本語 on the list,, although i use 日本語 in schildichat so it must be there somewhere

**Comment by autoteelar** [comment]
if its just borrowing the element translation thats okay and fine too, but i just think its important to have Normal Priority Translated at least, since its one of the things you see most while using the client

**Comment by SpiritCroc** [comment]
Maybe the translation exists for Element, but not for SchildiChat. If you're missing a translation, there's a button to add one.

**Comment by autoteelar** [comment]
wow ya nice, after logging in it just pops up like that 
![image](https://user-images.githubusercontent.com/76745649/197980689-bd3ddad1-e832-4e87-b92e-c66338b513da.png)

**Comment by autoteelar** [comment]
I'll try my best to figure this out and kink out any errors/missing info

**Comment by autoteelar** [comment]
is there a way to grab the ones that already exist on element?

**Comment by autoteelar** [comment]
and do you have to do them 1 by 1 individually for each device? i cant just apply it to all 3/4?

**Comment by autoteelar** [comment]
i think i figured it out, does clicking All Strings work? i submitted a few lines,

**Comment by autoteelar** [comment]
oh i see, so its mostly for extra translations on top of elements? if so that might be easier

**Comment by autoteelar** [comment]
ill just change it for each of them then :)

**Comment by su-ex** [comment]
Yes, we only have translations there for our own strings. All strings which Element contains as well need to be changed in their weblate.

Thanks for translating to your language!

GitHub recently calls closed issues completed for whatever reason, I've indeed only closed this because this is the wrong place to take action. Translations and weblate usually break when messing with the files directly, that's why we refrain from doing so.
Also please understand that it might seem obvious to you what to change since it's your language but for me those are just glyphs.
Actually, we provide weblate as graphical user interface so that our users can step in for what we can't do ourself: Translating to their language. 🈴✏️
Feel free to summarize what would have helped you to know so that we can put it into our readme and help others translating as well. 🙃

**Comment by autoteelar** [comment]
i do agree it is the wrong place to take action, my bad on that, at that time, this was the closest place i knew then but got pointed in the right direction :) so i thank you for that

and yes, i do understand they dont have any meaning attatched and almost just seem like abstract paintings if you don't know what the symbols mean, but i did try my best to explain it in the most cohesive way i could, at least for the word i gave in the example with definitions, im sure you can at least see the visual similarity between them, how they are almost the exact same word besides the first character of each word, one meaning "low" and one meaning "normal" so to speak. 

and yeah ok, to summarize, hmm, id say the best way would maybe add a dedicated translate part to the readme? one that just tells you where and how to translate schildichat, I'd say tell them where to go and what to click to a degree too, as it seems slightly confusing for new end users or translators who haven't used that website before, i think that would make it hassle free for anyone to translate what they want :D thank you
