### ISSUE TITLE
is applying the schildichat skin to latest commits of element possible?

### ISSUE THREAD

**Issue by autoteelar** [SchildiChat/schildichat-desktop#158]
hii, i want to try out the latest element features, but i need to pull from git for that, i was wondering if its possible to apply the schildichat stuff to the latest element git while building. i was using element today and i just cant i really like schildichat corners and group all people and chats in the same category, so if this is possible i would love to try it!

**Comment by su-ex** [comment]
There are options in the appearance settings to change corner roundness ("mixed" is the same as Element) and to disable the unified room list.

**Comment by autoteelar** [comment]
yes i am aware of the settings in the actual schildichat app, do you understand what i am asking?

i want to compile the latest git of element-web or element-desktop but i want to APPLY schildichats UI to it, how do i do that? just follow the instructions in the index? i thought i would ask if its possible before investing into something that may or may not even work

**Comment by su-ex** [comment]
You'll have to merge upstream Element into SchildiChat, that's what I do with new upstream releases.
You might want to take a look at `./merge_upstream.sh` in the schildichat-desktop repo to ease that process.

**Comment by autoteelar** [comment]
thank you :) i will do my best
