### ISSUE TITLE
Element Bug in 1.11.8, fixed in later Element versions.

### ISSUE THREAD

**Issue by autoteelar** [SchildiChat/schildichat-desktop#159]
i thought i would post this here just to let you know, me and a few friends were testing video rooms but never managed to get the new element call video rooms work from 1.11.8-1.11.10, but in the latest element release a few days ago (1.11.11) it works flawlessly out of the box for me and all my friends who haven't managed to get it to work, so i think element did something client side. so i would just recommend to at least use that version, preferably later, the next time you update SchildiChat :D thanks

i tried the nightly and it seems to fix even more weird bugs relating to video chat, maybe hold off a bit or release a patch for it or something? as of right now group chats only work through jitsi, idk updates only seem to release every few months, right now is kind of more pivotal than ever though because of these video rooms, so like i wouldnt want you to update to something with a bug in it, then element patches it the next day, just for schildichat users to need to wait months for the next release, you see? 

of course end users can build themselves, but dont you agree you would like the best end user experience possible? currently i feel schildichat already does that over element, which is one of the reasons i use it.

**Comment by su-ex** [comment]
Latest Element is now merged into schildi. If we don't discover any grave issues in the next few hours, it will be released.

The release schedule is based on my available time. This is nothing I can fix right now while I work on schildi desktop basically alone.

**Comment by autoteelar** [comment]
your efforts are always much appreciated thank you

**Comment by autoteelar** [comment]
i love helping with schildichat, ill do everything i can, but my experience isnt as grand as yours, i can do bug reports and do translations tho :D
