### ISSUE TITLE
Can't set up encryption or cross-signing when initiating session with CAS

### ISSUE THREAD

**Issue by retiolus** [SchildiChat/schildichat-desktop#162]
I can't set up encryption or cross-signing when initiating my session with CAS.

My account on the Synapse server is created with LDAP, I initiate the session on Schildichat with this account using CAS, I am asked for a password to activate these two options but it does not seem to be the same password as the LDAP user, what to do?

**Comment by su-ex** [comment]
You should definitely ask that Element, because this is definitely an upstream issue.
You can keep this issue here if you want, but it will linger here forever due to my lack of knowledge and time to fix it.
