### ISSUE TITLE
setting space/room pfp sometimes doesnt display properly

### ISSUE THREAD

**Issue by autoteelar** [SchildiChat/schildichat-desktop#171]
i created a new space and set the name and pfp, but the pfp wouldnt apply. so i set it on develop.element.io and it set fine, so i tried to set it again on schildichat which i could see the picture applied but when i try to change it from schildichat it acts as if it removes the profile picture when i hit upload, pic the picture, and hit the save changes button. so i assume its removing it? can you confirm if this bug happens on your end? using latest release 1.11.13 desktop edition on linux, with appimage

**Comment by autoteelar** [comment]
i can confirm it works for group chats

**Comment by autoteelar** [comment]
it seems like the image doesnt actually get removed, it is there and it uploads but it doesnt display properly. if i click the empty letter pfp to fullscreen it i can see the picture.

**Comment by su-ex** [comment]
Does the same happen with Element v1.1.13?
