### ISSUE TITLE
diacritics / accented characters (áéíóúçć etc.) initially appear then are stripped by client

### ISSUE THREAD

**Issue by Patola** [SchildiChat/schildichat-desktop#172]
schildichat version: 1.11.13.sc.1-1 from AUR on Arch Linux
DESCRIPTION: trying schildichat as a new matrix desktop after been using element for years. All is well but when I type accented characters in the text box for the group chat or private chat, they initially appear but right after I finish a word with spacebar it disappears. If I try to send the text even before I finish the word, the "send message" arrow appears greyed out.

I have ibus running and I set the QT IM module to it (`GTK_IM_MODULE=ibus`) but even when I unset this variable the same thing happens.

This precludes my communication because I take part of Brazilian Portuguese and Polish chats and in these languages the diacritics are essential for understanding.

**Comment by su-ex** [comment]
So the same does not happen with Element v1.1.13?

**Comment by Patola** [comment]
Not sure, I'm using element-desktop 1.11.10-2. But it does not happen with any other application, QT or otherwise, only schildichat.

**Comment by su-ex** [comment]
Please compare with the same version of Element.

**Comment by Patola** [comment]
Teste with element-desktop 1.11.14, it works perfectly, as did 1.11.10-2 before.

**Comment by su-ex** [comment]
1.11.14 is not the same as 1.11.13, maybe it was a regression and has been fixed recently.

**Comment by Patola** [comment]
I couldn't find any package with 1.11.13, not even in flatpak. Will keep trying and might be that I'll have to git checkout and compile it myself.

**Comment by su-ex** [comment]
I've just tested this with [v1.11.13-sc.1](https://github.com/SchildiChat/schildichat-desktop/releases/tag/v1.11.13-sc.1)
Toggle commit message and [v1.11.14-sc.0.test.1](https://github.com/SchildiChat/schildichat-desktop/releases/tag/v1.11.14-sc.0.test.1), both didn't strip any of those characters (though I don't know how to type ç) after hitting space, typing another word and sending.

**Comment by su-ex** [comment]
Maybe try without flatpak if this is what you're using now.

**Comment by Patola** [comment]
I hadn't used schildichat's flatpak, it was the packaged version.
Using the flatpak version now (1.11.13-sc.1) and diacritics work correctly though. I guess I'll have to stick to it for the time being.

**Comment by su-ex** [comment]
Which os do you use (so which of the packaged versions)?

**Comment by Patola** [comment]
schildichat version 1.11.13.sc.1-1 from AUR on Arch Linux
as I said on my first message

**Comment by su-ex** [comment]
Oops, indeed. But I've been not sure what you might have tried now. Weird that it doesn't work for you but for me (I'm on Arch as well). Maybe try `schildichat-desktop-git` as it uses system electron. Maybe also try if you have the same issue on https://app.schildi.chat (with different browsers).

**Comment by Patola** [comment]
Tried to install schildichat-desktop-git but it fails to clone the submodules directories for compiling, will need to look further into it, unfortunately these days I ain't having much time.
