### ISSUE TITLE
ring sound of first call is not played

### ISSUE THREAD

**Issue by Cyborgscode** [SchildiChat/schildichat-desktop#173]
Version von SchildiChat: 1.11.8-sc.1
Version von Olm: 3.2.12
OS: Linux Flatpak

If I audio/video-call someone for the first time after schildichat started, the ringing sound is not played.

**Comment by su-ex** [comment]
Does the same happen with Element (make sure you compare the same versions, SchildiChat v1.11.13-sc.1 means it's based on Element v1.11.13).
This is very likely upstream, nothing changed here.
