### ISSUE TITLE
Mobile guide

### ISSUE THREAD

**Issue by su-ex** [SchildiChat/schildichat-desktop#18]
- [x] No iOS app --> use Element there instead
- [x] Branding
- [x] For Android: link to https://schildi.chat/android
- [ ] Maybe allow custom url via config (might be easier than redirecting via server)
- [ ] Redirect to https://schildi.chat/web/mobile-guide for the SchildiChat instance on https://app.schildi.chat

**Comment by alexander-potemkin** [comment]
@su-ex , I tried to google, but didn't find it - what's the reason an iOS app is out of scope?

**Comment by Kloenk** [comment]
Both (upstream) iOS and Android apps are native, not a cross platform app. So we would either have to fork element-ios and maintain a third project, or create something completely new, which is probably same or even more work. I (as somewhat externe maintainer) do some work on http://github.com/niochat/nio/ but for personal reasons for all maintainers there, its currently not usable.

**Comment by SpiritCroc** [comment]
1. Lots of work, to deal with the worst of the Element codebases (from what I've heard from various sources)
2. The SchildiChat core developers are not interested in buying Apple gear, and thus also not in developing for it
3. People interested in buying Apple gear tend to have a different taste in design than the SchildiChat core team

**Comment by alexander-potemkin** [comment]
@Kloenk ,  @SpiritCroc , thanks for the prompt and detailed answer!

**Comment by TonyBostonTB** [comment]
Excluding platforms is not how it should be done. That's the same as with applications only built for e.g. windows. Though, I totally understand that it's a lot of work. Sounds snowflaky anyway.

**Comment by SpiritCroc** [comment]
> Excluding platforms is not how it should be done. That's the same as with applications only built for e.g. windows. Though, I totally understand that it's a lot of work. Sounds snowflaky anyway.

You're making it sound like we exclude platforms from a common codebase. In reality, desktop, Android and iOS apps are completely different apps, so supporting iOS would be re-doing all work done for the other platforms. Also you make it sound like we're a business with endless resources, rather than just being some hobby developers who barely have enough time to even keep those platforms we're actually interested in maintained. That's not reality.

**Comment by alexander-potemkin** [comment]
Guess one can always sponsor the features he/she needs, given there is an interested developer and/or if he/she is not interested to implement it all by him-/her-self.
