### ISSUE TITLE
Latest release fails on "Modern" appearance setting when semicolon is pressed.

### ISSUE THREAD

**Issue by BrotherIAmPinnedHere** [SchildiChat/schildichat-desktop#183]
Using the Linux appimage of release 1.11.22-sc.1, typing a semicolon on a server with several custom emojis uploaded through Fluffychat, causes an error. The chat goes blank, and a button requesting you to clear the cache appears.

**Comment by su-ex** [comment]
If it's only with the "modern" layout, that would explain why I couldn't reproduce this till now. I didn't test that separately.

**Comment by BrotherIAmPinnedHere** [comment]
> If it's only with the "modern" layout, that would explain why I couldn't reproduce this till now. I didn't test that separately.
It seems to happen with message bubbles, too. It didn't happen with custom emojis in prior releases. Perhaps there's an issue with how it reads global room emojis?
