### ISSUE TITLE
In notifications Can't load this message (m.room.message) error occurs for all offline notifications

### ISSUE THREAD

**Issue by Cknight70** [SchildiChat/schildichat-desktop#185]
Hi, I recently deployed Schildi chat for web on my site. using [schildichat-web-1.11.22-sc.1.tar.gz](https://github.com/SchildiChat/schildichat-desktop/releases/download/v1.11.22-sc.1/schildichat-web-1.11.22-sc.1.tar.gz) on releases page.

Clicking the bell to view notifications shows a list of errors
![image](https://user-images.githubusercontent.com/28763729/219320821-4636b701-59cb-42fb-93ff-385e172903e8.png)

New notifications while I am online will appear properly
Refreshing the page will cause all the notifications to display improperly again.

Here's the source from one of these notifications
```
{
  "content": {
    "body": "Cknight70: i like this client",
    "format": "org.matrix.custom.html",
    "formatted_body": "<a href=\"https://matrix.to/#/@cknight70:myepicserver.com\">Cknight70</a>: i like this client",
    "msgtype": "m.text"
  },
  "origin_server_ts": 1676528284848,
  "sender": "@epicuser:myepicserver.com",
  "type": "m.room.message",
  "unsigned": {
    "age": 9749826
  },
  "event_id": "$correcteventid",
  "room_id": "!correctroom:id.com"
}
```

I confirmed at least one other of my users are also experiencing this. 

After reading my logs, I'm not super comfortable posting everything in them but would be happy to assist if needed. Thanks

**Comment by KaKi87** [comment]
Hello,
In which version will this fix be released ?
Thanks

**Comment by su-ex** [comment]
@KaKi87 Whenever the next release will happen (soon™ if we don't notice any grave bugs).
