### ISSUE TITLE
Display all message history to the beginning of the room

### ISSUE THREAD

**Issue by Tcll** [SchildiChat/schildichat-desktop#186]
message history is currently limited and refuses to scroll any farther than the limit
where as alternatives like Cinny and Nheko can scroll back to the beginning of the room

this is good for keeping updated key backups for all encrypted messages
rather than only the keys for the messages that have previously been seen
(messages between the limit and last viewed message are lost)

**Comment by su-ex** [comment]
It's not limited, it was already possible to scroll back to the beginning of a room, but it seems there happened something weird upstream now which makes a room steadily scroll when e.g. clicking a matrix.to-link which leads to the beginning of a room. Very weird indeed, but I cut reproduce this with Element, so this is an upstream issue.

**Comment by Tcll** [comment]
I can only scroll up to a limit
it refuses to load anything past that point at all, no matter how much I scroll up, reload the room, or whatever

but anyways, I'm only requesting because you guys fixed search :)
so I'd figured you'd fix yet another thing element broke
lol

**Comment by Tcll** [comment]
oh, I should probably mention I'm using LibreWolf

Cinny can scroll back to the start just fine on LibreWolf, but Schildichat only scrolls to that limit

**Comment by su-ex** [comment]
Can you scroll to the beginning of the desktop room through e.g. https://matrix.to/#/!eSTlitQAfqxWWEHMFD:matrix.org/$UbyoWn8Krx-jdKg0xMqbtlDBnWkVTeeg_UKyf1RBPQM?via=schildi.chat&via=supercable.onl&via=spiritcroc.de ?

**Comment by Tcll** [comment]
in fact
here's an image showing the issue in action
it WILL NOT load any further past this point no matter what I do:
https://jump.matthewevan.xyz/i2p/pxbcwxbhxj2wusliwhrb6ym4vcwpihztuf2tfjejrcdzqrmnjuoa.b32/_/02d733d87311dabfb52e0f4dc88609a546382fdde2cd897d842755bb0b6b45b0

**Comment by Tcll** [comment]
> Can you scroll to e.g. the beginning of the desktop room through

I don't use electron apps
and specifically don't trust it with Schildi since I'm blocking canvases from collecting data in LibreWolf
where as shadow-profiling malware could run unrestricted in an electron app if the devs haven't made any effort to prevent as such

**Comment by su-ex** [comment]
> in fact here's an image showing the issue in action it WILL NOT load any further past this point no matter what I do: https://jump.matthewevan.xyz/i2p/pxbcwxbhxj2wusliwhrb6ym4vcwpihztuf2tfjejrcdzqrmnjuoa.b32/_/02d733d87311dabfb52e0f4dc88609a546382fdde2cd897d842755bb0b6b45b0

If this should be animated, it isn't.



> > Can you scroll to e.g. the beginning of the desktop room through
> 
> I don't use electron apps and specifically don't trust it with Schildi since I'm blocking canvases from collecting data in LibreWolf where as shadow-profiling malware could run unrestricted in an electron app if the devs haven't made any effort to prevent as such

Well, just send the link to any room while already inside schildi with whatever and click it, then it will open inside your current schildi and you don't need electron.

**Comment by Tcll** [comment]
> If this should be animated, it isn't.

I don't have a way of recording it
but it's still at that shot
it won't load any farther

> then it will open inside your current schildi

also matrix room links don't work for me
but that's not an issue :P

the issue is I can't scroll back to the start of the room like I can with Cinny (fork of Element)

**Comment by Tcll** [comment]
update

looks like if you go beyond the limit

the moment you scroll back down to the limit, the messages above the limit are clipped and you're stuck back at the scroll limit

**Comment by Tcll** [comment]
another update
looks like there's still a limit even if you quote beyond the initial limit

looks like the best workaround is to quote the very first message of the room in a client with unlimited history

I hope you remove the history limit in Schildi too :)

**Comment by SpiritCroc** [comment]
This may sound obvious, but are you using the same account for SchildiChat and the other clients you mentioned? The only case that I remember where I couldn't scroll back in history was that my server hadn't backfilled enough federated history yet. That and sometimes it's not possible to read old messages in encrypted chats before the time you joined, so since you won't be able to decrypt anyways, the client hides them.

**Comment by Tcll** [comment]
I created the room and have the entire history for it in both Cinny and Nheko, and can scroll back to it freely

Schildichat just refuses to scroll back past a specific limit of messages (see the image above, I still can't view anything prior)
Element does this as well, they implemented it some time ago
it seems to be a feature strictly designed just to cause inconvenience as there's no reason it shouldn't be able to load past that point
(in fact a reason I switched to Cinny, aside from the memory issues where Element seems to use RAM for no reason at all)

also regarding inability to decrypt
I've actually had a weird issue where I can see a message in Cinny, but Schildi refuses to decrypt it regardless
even while the friend who posted the message is online

it's a shame Nheko doesn't work without dbus or I could probably poll it from there :P
but that's a separate issue that ends up resolving itself later

I just want to be able to scroll past the limit at that

basically, I can scroll down to here from a reverenced quote beyond the point:
https://jump.matthewevan.xyz/i2p/pxbcwxbhxj2wusliwhrb6ym4vcwpihztuf2tfjejrcdzqrmnjuoa.b32/_/e1315f5a5cf0d9b70034132bd846b9baa75f1fe8616951552b4389e9bfa16cc7
but if I scroll down by 1 click, it clips everything back to the image above, and shoves me down where I can't scroll up:
https://jump.matthewevan.xyz/i2p/pxbcwxbhxj2wusliwhrb6ym4vcwpihztuf2tfjejrcdzqrmnjuoa.b32/_/02d733d87311dabfb52e0f4dc88609a546382fdde2cd897d842755bb0b6b45b0
it's a hard limit somewhere that prevents loading any further messages that was added into Element some time ago
(I don't really remember exactly when, but it's been a few years now)

meanwhile Cinny just displays everything without issue:
https://jump.matthewevan.xyz/i2p/pxbcwxbhxj2wusliwhrb6ym4vcwpihztuf2tfjejrcdzqrmnjuoa.b32/_/d14c4fa7ecee87d72c080e518b02b3be0d8fde92a3231c2cd965d6dae08a5cef
and Nheko too
this is specifically an intended feature of Element that only exists to cause problems
much like how they broke searching

**Comment by SpiritCroc** [comment]
> this is specifically an intended feature of Element that only exists to cause problems much like how they broke searching

If you don't have evidence to justify that claim, like a code pointer or some commit that shows that, it's not really helpful to blame people here. Still sounds like a bug to me. Since you have it on Element as well, probably best to report to them.

**Comment by Tcll** [comment]
what I'm trying to say is I remember conversations about it in the Element room quite a while back (I left it after I stopped using Element for their bad decisions (not just this issue, but like how they want you to pay for custom emojis as well, along with many others))
anyways, the limit was added intentionally for certain, and won't be removed afaik (part of why I quit using Element years ago)
maybe it's to force people to use the desktop app if anything, idk, but it's still unreasonably problematic none the less
all I'm asking is if you could restore it like you've done with search

it sucks how all matrix clients just seem to have a signature thing you have to give up for another feature
like with Cinny, you have to give up Search and stability
Element you have to give up custom emojis, message history, and search
Nheko you have to give up moderation controls, room organization, and good quality aesthetics (I forget if it could do custom emojis or not like Cinny can)

but yeah, since Schildi seems to fix what Element intentionally breaks, I was really hoping you'd fix message history as well... u3u
custom emojis are another issue entirely, which I'll create an issue for if it bothers me enough and nobody else does

**Comment by Tcll** [comment]
minor update (more information on things)

one of my friends sent me this from mobile element
https://jump.matthewevan.xyz/i2p/pxbcwxbhxj2wusliwhrb6ym4vcwpihztuf2tfjejrcdzqrmnjuoa.b32/_/e458fc81983440f50842f8749de318878b7a219dcfdf002a0a0f7b19b728e593

looks like they even provide the option to disable the history limit
not sure if the option being disabled means you can't disable it though

but yeah, it may be easier to fix than initially thought
probably even easier than what you do to fix search
