### ISSUE TITLE
Custom theme username colors broken (1.11.22-sc.1)

### ISSUE THREAD

**Issue by ghost-amnesiac** [SchildiChat/schildichat-desktop#187]
Custom themes can no longer specify custom username color palettes and all usernames are displayed in Schildi green.

Reference theme is [Covalence Dark](https://github.com/aaronraimist/element-themes/blob/master/Covalence/covalence.json?raw=1).

Broken in 1.11.22-sc1:
<img width="645" alt="broken username colors" src="https://user-images.githubusercontent.com/123417798/225466575-85429d19-c121-45ea-bc56-43e6947f7dac.png">

Working back in 1.11.13-sc1:
<img width="762" alt="working username colors" src="https://user-images.githubusercontent.com/123417798/225466430-17f94804-987f-4f60-a6fd-075078b02faf.png">

Element 1.11.25 for reference:
<img width="645" alt="working username colors" src="https://user-images.githubusercontent.com/123417798/225466887-7743e9cf-a7d4-4f27-9609-0672f9990cc7.png">

**Comment by su-ex** [comment]
It's not broken, it's an option.
Just set the user name color mode to mxid in the advanced theme settings section of the appearance settings.
