### ISSUE TITLE
Default setting point to `meet.jisti.org` that has a 5 minute limit

### ISSUE THREAD

**Issue by nuke-web3** [SchildiChat/schildichat-desktop#192]
https://github.com/vector-im/element-desktop/issues/983

I should have filed that one here as I am actually using SchildiChat desktop, I _think_ it's as simple as a changing a default config setting somewhere for the client (like here https://github.com/SchildiChat/element-web/blob/f3e6edbe968d21abe48fc64cb2fe93fffd69c4fd/config.sample.json#L41 ), but that is unclear.

**Comment by su-ex** [comment]
I see. Then we should probably switch back to Element's jitsi instance by default.

**Comment by Cyborgscode** [comment]
it also has an active account requirement now, so you can't just open a new groupchat anymore. Element has the new groupcall feature ready for testing, so i suggest to switch to it.

**Comment by NukeManDan** [comment]
I have used https://jitsi.riot.im/ without issue for a while now. Unclear if this will be supported long term :shrug:
