### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Diegiwg** [SchildiChat/schildichat-desktop#194]
[Pacstall](https://github.com/pacstall/pacstall) is a community-driven AUR-like package manager for Ubuntu. We have an ongoing pull request to add [schildichat-deb](https://github.com/pacstall/pacstall-programs/pull/3661) to our repository.

We have a few questions for you:
* Would you like to maintain the pacscript (similar to a PKGBUILD) yourself? We can maintain it for you if you decide not to.
* Could you include a section in your documentation showing Pacstall as a valid method of installation for schildichat-deb for Debian/Ubuntu users? We could make a pull request for that if you want.

**Comment by SpiritCroc** [comment]
Thanks! We do not have enough resources available (or motivation for that matter, since we're both on Arch) to maintain this ourselves, but feel free to maintain the package and create a PR for our [website](https://github.com/SchildiChat/website) to promote it!
