### ISSUE TITLE
Max font size of 20pt may still be too small for some users

### ISSUE THREAD

**Issue by magicalskye** [SchildiChat/schildichat-desktop#200]
Hello, I am a person with a very minor visual impairment but I need a larger font size. 20 point is not enough for me without glasses, and it is definitely not enough for any partially sighted or legally blind people who may want to use this program.

**Comment by SpiritCroc** [comment]
Just wondering, wouldn't it be easier to use your operating system settings at some point to make all applications bigger, or is SchildiChat the only one which has too small text?

**Comment by magicalskye** [comment]
setting the font size over the desktop environment makes EVERYTHING bigger, including window decorations and other stuff that you don’t actually NEED to read, which takes up a lot of space. so i generally set a smaller font size there, that i can read just barely with some squinting, in order to have more space available for the actual content at a comfortable size. this is especially true for users that need Very Large font sizes (40-100pt)

also i have no idea why that is, but when i set “20 pt” in schildichat it’s still smaller than the “16 pt” i have set in other applications using the same font. but i am too lazy to try and figure that out and at any rate the problem disappears if the font size limit is removed or increased significantly

thank you for your time
