### ISSUE TITLE
Gnome-keyring for other app locking access

### ISSUE THREAD

**Issue by JetpackJackson** [SchildiChat/schildichat-desktop#207]
I had to install gnome-keyring in order to use Protonmail's import-export app, but now every time I open Schildichat (edit: for the first time after I start the computer), a gnome-keyring popup appears, and I have to enter my Protonmail password in order to continue to Schildichat and read new messages. If I click cancel, I can view Schildichat but it doesn't refresh any messages.
![primary_20230822165930](https://github.com/SchildiChat/schildichat-desktop/assets/88674707/760649bb-5f37-42e9-91aa-569e9038de58)
What can I do to fix this? I never set up anything with Schildichat to use gnome-keyring, so I don't know why it's trying to use it.
Thanks in advance.

**Comment by Cyborgscode** [comment]
the gnome keyring needs to be unlocked. Normally this is done on login time with the password supplied. 
Schildichat safes keys to it as any other app should do, so you get asked now on the startup of any app using it, to unlock it. 

erase the keystore, recreate the ring with your loginpassword and add the keyringd to your DE startup, than add the keys for schildi and proton again. Disclaimer:  "Should work" as in "untested" . SEAHORSE can be of help here.

**Comment by JetpackJackson** [comment]
Alright, I'll try that out when I get home.

**Comment by JetpackJackson** [comment]
Alright, thank you, this fixed it. Since it was an error with my own usage/understanding of the keyring, I'll close this issue.
