### ISSUE TITLE
[FEATURE REQUEST] Add support for parsing mxc urls as images in reactions

### ISSUE THREAD

**Issue by Sid127** [SchildiChat/schildichat-desktop#208]
This exists in SchildiChat android, but not on Desktop or Web. It'd be helpful to users who use Matrix with bridges as custom reactions on some platforms show up as mxc urls on SchildChat, with there being no way for a user to figure out what the reaction actually is without logging into the source platform

**Comment by SpiritCroc** [comment]
Nevermind, upstream merged it, so we will get it once we merge the upstream version that has it: https://github.com/matrix-org/matrix-react-sdk/pull/11087
