### ISSUE TITLE
Update to `1.13.40`

### ISSUE THREAD

**Issue by luixxiul** [SchildiChat/schildichat-desktop#211]
SchildiChat has not updated since `v1.11.30-sc.2` while the upstream is at [`v1.11.40`](https://github.com/vector-im/element-web/releases/tag/v1.11.40). It should be updated to the latest version before it will become too difficult to keep it synced with the upstream…

This intends to be a friendly reminder.

**Comment by su-ex** [comment]
https://matrix.to/#/!eSTlitQAfqxWWEHMFD:matrix.org/$zu5cW3DCREAg1PicoBqgOJukME-uO5ZyjitKZTmg3aU?via=supercable.onl&via=matrix.org&via=nomadserver.us and subsequent messages.
