### ISSUE TITLE
[FR] An option to spoiler part of a message

### ISSUE THREAD

**Issue by 1bcb** [SchildiChat/schildichat-desktop#219]
In FluffyChat as well as Discord, it's easy to hide only part of a message behind a spoiler warning by wrapping the spoilers with pairs of vertical bars like this: ||spoilery stuff goes here.||

I am requesting that a similar feature be added to SchildiChat.  Currently, the only way I know of to create spoilers in SC are either the /spoiler command, which is limited to spoilering the entire message, or `<span data-mx-spoiler>Hidden content here!</span>`, which requires you to use an HTML message and takes longer to type.

**Comment by lexi-the-cute** [comment]
yes please
