### ISSUE TITLE
ERROR (Maybe not Schlidi's fault) when compiling from source.

### ISSUE THREAD

**Issue by SlimTux** [SchildiChat/schildichat-desktop#221]
Hello, I followed the instructions in the documentation and got an error when compiling from source (Arch Linux)

I personally think that is an issue with the node(yarn) version (Schlidi has probaly not upgrade to a newer version, but i may be wrong)

![pic-selected-231205-1638-06](https://github.com/SchildiChat/schildichat-desktop/assets/117015097/020687b4-cf2f-41ac-9b7f-1998879fe5e7)

## How to reproduce the error
> $ mkdir $HOME/APPS/Chat
> $ cd APPS/Chat
> $ git clone -b master --recurse-submodules https://github.com/SchildiChat/schildichat-desktop.git
> $ cd schildichat-desktop
> $ make setup 

#### I dont know how to use labels and publish a proper Issue

**Comment by SpiritCroc** [comment]
If I remember correctly, best is to use [nvm](https://aur.archlinux.org/packages/nvm) to manage node versions.
For Arch in particular, it can sometimes be useful to check the schildichat-desktop-git AUR [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=schildichat-desktop-git) to compare how others build it.
Looks like I'm personally using node 16 to build right now, just like the AUR recipe.

**Comment by SlimTux** [comment]
Thank you @SpiritCroc, it solved my issue.
