### ISSUE TITLE
SchildiChat crash with core dump under hyprland on wayland

### ISSUE THREAD

**Issue by thelmuxkriovar** [SchildiChat/schildichat-desktop#222]
# Environment:

- **Distro**: NixOS
- **Display Server**: Hyprland (Wayland)
- **XDG Portal**: GTK

# Description:

When attempting to launch the SchildiChat desktop application on a system using Hyprland (a Wayland compositor), the application crashes, resulting in a segmentation fault and a core dump. This issue occurs immediately upon starting the application and prevents any further interaction or use of the software.

The application successfully launched on the first attempt, before configuring user account, but subsequently crashes on subsequent attempts, resulting in a segmentation fault and a core dump. 

# Steps to Reproduce:

1. Launch SchildiChat-Desktop
2. See crash
3. Cry

# Expected Behavior:

SchildiChat should launch successfully without crashing, allowing for normal usage.

# Actual Behavior:

The application crashes immediately upon launch. Launching it from the terminal reveals a segmentation fault:

```
$ schildichat-desktop
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Resetting the UI components after locale change
Segmentation fault (core dumped)
```

# Additional Details

Interestingly enough element seems to launch successfully every time

**Comment by Kloenk** [comment]
as https://github.com/NixOS/nixpkgs/pull/272270 schildi got removed from nixpkgs waiting for the next upstream release. you can try to override the electron used.
