### ISSUE TITLE
Can't connect to Element Call

### ISSUE THREAD

**Issue by Obamium69** [SchildiChat/schildichat-desktop#228]
**Steps to Reproduce:**

1. Enable the Element Call feature in Labs.
2. Join a room where Element Call is enabled.

**Expected Outcome:**

- It is possible to join the call

**Actual Outcome:**

- The connection is timing out:

 https://github.com/SchildiChat/schildichat-desktop/assets/61025357/3ad4b737-b4b9-4e47-a16d-80fe01ca9f76

-  The following error message is visible in the browser console:
![grafik](https://github.com/SchildiChat/schildichat-desktop/assets/61025357/8e497d7c-0d1b-4f04-b856-e4e3889d8c6d)

**Note:**

- Creating and joining an Element Call room with  Element Nightly: 2024010101 works.
- The issue is present on the desktop app and via browser

**Version (both dekstop app and browser version):**
SchildiChat: 1.11.30-sc.2
Olm: 3.2.12

**System info:**
OS: EndeavourOS Linux
Kernel: 6.6.8-zen1-1-zen
DE: KDE Plasma 5.27.10
WM: KWin (X11)
Browser: Firefox 121.0

**Comment by Obamium69** [comment]
The issue is stll present

**Comment by Cyborgscode** [comment]
Version von SchildiChat: 1.11.36-sc.3
Version von Olm: 3.2.14

an "Element Call" has been started in a room, that DOES NOT support it and now, this call is running for 3 days but can not be stopped or removed from UI.

**Comment by Obamium69** [comment]
Still not fixed

**Comment by su-ex** [comment]
With a switch to the newer codebase currently in development (alpha release in https://github.com/SchildiChat/schildichat-desktop/releases/tag/v1.11.81-sc.0.test.0 ), this will be resolved.
It won't be fixed for the old codebase anymore, only thus adding the label.
