### ISSUE TITLE
v1.11.36-sc.2 is not working on linux

### ISSUE THREAD

**Issue by arkadym** [SchildiChat/schildichat-desktop#233]
Just download AppImage and upgrade from 1.11.30, now keep getting error. I tried remove my profile (.config/SchildiChat folder) and re-login, keep see same error
![image](https://github.com/SchildiChat/schildichat-desktop/assets/7422012/74d7c60e-b6b6-4ed0-aca4-d1528a50d3e8)

Update: I were able to downgrade 1.11.30, seems like upgrade do not do any breaking changes to profile. But yet is not usable here

**Comment by su-ex** [comment]
@arkadym Can you please post the browser devtools console output as well? Wondering why it crashes entirely for you while the room list loads for luixxiul.

**Comment by luixxiul** [comment]
> @arkadym Can you please post the browser devtools console output as well? Wondering why it crashes entirely for you while the room list loads for luixxiul.

Sorry, I have got the same error message on the right chat pane, which I omitted from the screenshot.

**Comment by su-ex** [comment]
Ok, thanks, then it makes sense.

**Comment by su-ex** [comment]
Just fyi for the meantime: 
I found out how to reproduce, it's the "Collapse additional buttons" preference setting disabled.
Enable it and it will work in the meantime.
