### ISSUE TITLE
missing `universal_by_nyantec.dmg` artifact for the most recent two releases

### ISSUE THREAD

**Issue by chenrui333** [SchildiChat/schildichat-desktop#245]
👋 looks like for the most recent two releases, the `universal_by_nyantec.dmg` artifact is missing. Raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-cask/pull/170641

**Comment by SpiritCroc** [comment]
We can no longer provide mac builds, compare https://matrix.to/#/!eSTlitQAfqxWWEHMFD:matrix.org/$Nr1nynMuQM7T7M0pMYNFyVIIQopAzH0VPdiNETA9Hko?via=schildi.chat&via=matrix.org&via=nomadserver.us and context - we currently have nobody with an appropriate Apple certificate to build it for us.
