### ISSUE TITLE
Schildichat UI is broken on arch linux

### ISSUE THREAD

**Issue by Juggo0** [SchildiChat/schildichat-desktop#248]
Recently I updated arch linux and for some time schildichat UI has completely been broken. (Not sure when exactly it broke, I only noticed this yesterday.)
Sometimes it's just a black or grey screen, sometimes it looks corrupted:

 ![img](https://github.com/SchildiChat/schildichat-desktop/assets/116839475/cbdc45ba-28d2-4ce0-a800-3fa8e937d7b1)

I can still hover over elements and click them, so the functionality is not broken, but the UI doesn't update or fix itself.

I tried running it on KDE and hyprland, but both end up like this.
Flatpak version doesn't have this issue.

**Comment by thorio** [comment]
What GPU are you running? I've noticed that it works on Nvidia, but breaks on my AMD iGPU.
Running Arch + xmonad, installed from the AUR bin package.
<details>
<summary>Screenshot</summary>

![image](https://github.com/SchildiChat/schildichat-desktop/assets/39875034/f3ba876a-63e0-4c5e-a001-2038ec6f244b)
</details>

**Comment by Juggo0** [comment]
I'm using an AMD Radeon RX 6800. I'm guessing that's the issue then?

**Comment by SpiritCroc** [comment]
I was able to work around this issue by launching schildichat with `--disable-gpu-driver-bug-workarounds`. ([source](https://bbs.archlinux.org/viewtopic.php?id=285507))

**Comment by SpiritCroc** [comment]
Update: after reading my link more, I figured that deleting `~/.config/SchildiChat/GPUCache` may be the better fix.

**Comment by Juggo0** [comment]
Yup, this fixed the issue. Thank you! :)

**Comment by Domoel** [comment]
How can I delete the cache of a flatpak app?

**Comment by ver4a** [comment]
> How can I delete the cache of a flatpak app?

rm -rf ~/.var/app/chat.schildi.desktop/config/SchildiChat/GPUCache
