### ISSUE TITLE
[bug] Flatpak does not automatically switch from/to dark theme when System theme is selected

### ISSUE THREAD

**Issue by luciofstars** [SchildiChat/schildichat-desktop#250]
leading to things like this:

![image](https://github.com/SchildiChat/schildichat-desktop/assets/171858414/da21d506-b087-4fc5-bbf7-4381418e3ae1)

(Using Fedora Silverblue, if that matters)

**Comment by qg-ae** [comment]
See the FAQ. With a switch to the newer codebase currently in development, this will be resolved. It won't be fixed for old codebase anymore.

**Comment by su-ex** [comment]
See the FAQ. With a switch to the newer codebase currently in development, this will be resolved.
It won't be fixed for the old codebase anymore, only thus adding the label.
