### ISSUE TITLE
Do not pull modification from Element web which breaks Firefox ESR (i.e support Firefox ESR)

### ISSUE THREAD

**Issue by b3** [SchildiChat/schildichat-desktop#251]
It seems that yesterday some Element web developer applied a policy which breaks the use of Element web for a **lot** of users as seen in [Element web issue `27682`](https://github.com/element-hq/element-web/issues/27682): Element web is no more usable under Firefox [Extended Support Release (ESR)](https://support.mozilla.org/en-US/kb/firefox-esr-release-cycle). Firefox ESR is the Firefox version distributed by Debian stable, RHEL, etc. It is also the base used by [TorBrowser](https://support.torproject.org/tbb/#tbb_tbb-42)!

SchildiChat is not yet affected.

I do not know the pull strategy from Element Web to SchildiChat but I think it would be a good strategy to enforce Firefox ESR support as asked in [Element web issue `27684`](https://github.com/element-hq/element-web/issues/27684) whatever Element decision concerning that issue will be.

Not supporting Firefox ESR implies to prevent using the tool for a **lot** of users (for instance all students of numerous universities, or administration, where Debian stable is the installed OS).

**Comment by SpiritCroc** [comment]
Since we're quite behind with merging upstream releases and it has become quite difficult to do so, there won't be any new schildichat-desktop release until we have something good enough started fresh on the latest Element release. So there won't be any updates soon and you'll be fine for a while.
Once we get running again, we likely won't have the resources to deviate from Element for changes of this kind though.

**Comment by isAAAc** [comment]
new esr version today in debian : 
```
# dpkg -l |grep firefox
ii  firefox-esr                              115.13.0esr-1~deb12u1                          amd64        Mozilla Firefox web browser - Extended Support Release (ESR)
ii  firefox-esr-l10n-en-gb                   115.13.0esr-1~deb12u1                          all          English (United Kingdom) language package for Firefox ESR
```
