### ISSUE TITLE
Black screen on EL9 - Skia shader compilation error

### ISSUE THREAD

**Issue by d1nuc0m** [SchildiChat/schildichat-desktop#252]
After some system updates, SchildiChat stopped working, with the main error being "Skia shader compilation error"

Using [v1.11.36-sc.3 RPM](https://github.com/SchildiChat/schildichat-desktop/releases/download/v1.11.36-sc.3/schildichat-desktop-1.11.36-sc.3.x86_64.rpm) on EL9

When launched, the main window appears but shows nothing, CLI output attached: [schildi.log](https://github.com/user-attachments/files/16172139/schildi.log)

Fixed purging the GPU cache with `rm -rf ~/.config/SchildiChat/GPUCache`

**Comment by SpiritCroc** [comment]
Sounds like https://github.com/SchildiChat/schildichat-desktop/issues/248
