### ISSUE TITLE
Schildi is offline after reboot over HTTP

### ISSUE THREAD

**Issue by ghost** [SchildiChat/schildichat-desktop#254]
Hello, I'm using Schildi with my own homeserver inside my local network and, for some reason, if I log in but I restart my computer, when it finishes booting Schildi is not reaching the homeserver anymore (which, again, is in my local network.)

It's important to take into account that I'm over HTTP and not HTTP/S, maybe it has to do with that.

(I can't use TLS because it's a local network.)

Thanks in advance for any help.

**Comment by qg-ae** [comment]
I guess this is just https://github.com/SchildiChat/schildichat-desktop/issues/170 as well.

**Comment by su-ex** [comment]
I guess this is just #170 as well.

**Comment by SpiritCroc** [comment]
Closing as duplicate
