### ISSUE TITLE
Connection to the server has been lost after reloading the application.

### ISSUE THREAD

**Issue by AlterNezKo** [SchildiChat/schildichat-desktop#260]
Hello !

O.S: Windows 10 
App version: 1.11.36-sc.3

SchildiChat suddenly loses connection when a change is made to a configuration that forces a reload of the App.  The only way to fix it is to log out and log back in, but that causes the configuration to be lost, forcing you to leave the program in its default state.

![image](https://github.com/user-attachments/assets/2224765f-2ade-4490-8265-f3dc56752ccc)

**Comment by SpiritCroc** [comment]
Duplicate of https://github.com/SchildiChat/schildichat-desktop/issues/170
