### ISSUE TITLE
Build of `lite` branch fails in `./merge_upstream.sh` with `fatal: 'upstream' does not appear to be a git repository`; `forall_repos add_upstream` prints `Don't know upstream repo for https://github.com/SchildiChat/schildichat-desktop.git`. | Can you provide prebuilt binaries?

### ISSUE THREAD

**Issue by dreirund** [SchildiChat/schildichat-desktop#262]
Ahoj,

I try to build the ["lite" branch of `schildichat-desktop`](https://github.com/SchildiChat/schildichat-desktop/tree/lite).

According to it's [`README.md`](https://github.com/SchildiChat/schildichat-desktop/blob/lite/README.md), I should do, after cloning,  
```
source merge_helpers.sh
forall_repos add_upstream
./merge_upstream.sh
```

However, `forall_repos add_upstream` does print four times `Don't know upstream repo for https://github.com/SchildiChat/schildichat-desktop.git`, and subsequent `./merge_upstream.sh` fails with `fatal: 'upstream' does not appear to be a git repository`.

I try to run:  
```
git clone https://github.com/SchildiChat/schildichat-desktop.git
cd schildichat-desktop
git checkout lite
source merge_helpers.sh
forall_repos add_upstream
./merge_upstream.sh
```

Full output of `forall_repos add_upstream`:  
```
Don't know upstream repo for https://github.com/SchildiChat/schildichat-desktop.git
Don't know upstream repo for https://github.com/SchildiChat/schildichat-desktop.git
Don't know upstream repo for https://github.com/SchildiChat/schildichat-desktop.git
Don't know upstream repo for https://github.com/SchildiChat/schildichat-desktop.git
```

Full output of `./merge_upstream.sh`:  
```
HEAD is now at 983cba2 [WIP] Add back theming
HEAD is now at 983cba2 [WIP] Add back theming
HEAD is now at 983cba2 [WIP] Add back theming
HEAD is now at 983cba2 [WIP] Add back theming
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

---

Can you provide prebuilt binaries, since self-compilation seems to be troublesome?

Regards!

**Comment by SpiritCroc** [comment]
Did you maybe forget to git clone with `--recurse-submodules`?
Though the branch is quite alpha, so it can happen it's not buildable in its current state. We'll probably consider prebuilt binaries once we have at least some of the Schildi theme back.

**Comment by dreirund** [comment]
> *Did you maybe forget to git clone with `--recurse-submodules`?*

You were right.

Now, `./merge_upstream.sh` errors with  
```
error: pathspec 'v1.11.77' did not match any file(s) known to git
```

How to get reliable build of the current state of work?

---

Details:

`forall_repos add_upstream` now does  
```
Adding upstream https://github.com/matrix-org/matrix-js-sdk.git
[...]
Adding upstream https://github.com/matrix-org/matrix-react-sdk.git
[...]
Adding upstream https://github.com/vector-im/element-web.git
[...]
Adding upstream https://github.com/vector-im/element-desktop.git
[...]
```  
and `./merge_upstream.sh` now prints  
```
HEAD is now at 9bbc32963 Merge tag 'v27.0.0' into sc
HEAD is now at 5a1c34750a Fix compact room list avatars
HEAD is now at 904c63786 Update version to 1.11.36-sc.3
HEAD is now at fb2931e Update version to 1.11.36-sc.3
Submodule path 'element-desktop': checked out '52715a8a8988d039ddb95266ff32acf38c98325f'
Submodule path 'element-web': checked out 'a0c654a2e4676bf48a7b87d0788fd20267f91f44'
Submodule path 'matrix-js-sdk': checked out '0300d6343fb26f12ff6a34452d3f7c176aa6c190'
Submodule path 'matrix-react-sdk': checked out '25e67beab6d2525fdc1adf4467b6f0da01415470'
Previous HEAD position was a0c654a2e v1.11.73
HEAD is now at 7b19facce v1.11.77
error: pathspec 'v1.11.77' did not match any file(s) known to git
```

**Comment by SpiritCroc** [comment]
> How to get reliable build of the current state of work?

As I said, it's alpha, so no, we're not at the point of a "reliable build" yet.

**Comment by SpiritCroc** [comment]
Since https://github.com/SchildiChat/schildichat-desktop/commit/8de7f8f8467db68fb9e01c8fb5d711114803d715 it's no longer necessary to run `./merge_upstream.sh` for building. Cloning with `git clone -b lite --recurse-submodules https://github.com/SchildiChat/schildichat-desktop.git` should now immediately yield buildable code as with the old instructions.
