### ISSUE TITLE
Tries to fetch non-existing `i18n/strings/en_US.json`.

### ISSUE THREAD

**Issue by dreirund** [SchildiChat/schildichat-desktop#266]
Ahoj,

when I build the latest state of this (on Arch Linux, using `make pacman`), after having worked around [this issue](https://github.com/SchildiChat/schildichat-desktop/issues/265), when I launch `schildichat-desktop`, it prints to the terminal the following error message:

```
Fetching translation json for locale: en_EN
Resetting the UI components after locale change
Changing application language to en-us,en,en,en
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: ENOENT: no such file or directory, open '/usr/lib/schildichat-desktop/resources/app/lib/i18n/strings/en_US.json'
    at Object.readFileSync (node:fs:448:20)
    at t.readFileSync (node:electron/js2c/node_init:2:10175)
    at loadJsonFile (/usr/lib/schildichat-desktop/resources/app/lib/utils.js:35:36)
    at AppLocalization.fetchTranslationJson (/usr/lib/schildichat-desktop/resources/app/lib/language-helper.js:77:45)
    at /usr/lib/schildichat-desktop/resources/app/lib/language-helper.js:90:39
    at Array.filter (<anonymous>)
    at AppLocalization.setAppLocale (/usr/lib/schildichat-desktop/resources/app/lib/language-helper.js:89:39)
    at IpcMainImpl.<anonymous> (/usr/lib/schildichat-desktop/resources/app/lib/ipc.js:81:36)
    at IpcMainImpl.emit (node:events:519:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86280) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/usr/lib/schildichat-desktop/resources/app/lib/i18n/strings/en_US.json'
}
```

The file `/usr/lib/schildichat-desktop/resources/app/lib/i18n/strings/en_US.json` does not exist, but `[...]/en_EN.json` does exist.

Regards!

**Comment by SpiritCroc** [comment]
I'm a little sceptical if your build environment is clean, what does `git status` say in the schildichat-desktop directory?

Apart from that, in the other issue you mentioned you're building the `master` branch, so the same comment applies that the master branch is not maintained right now, development happens in the lite branch until it's stable.

**Comment by dreirund** [comment]
> *you're building the `master` branch, so the same comment applies that the master branch is not maintained right now, development happens in the lite branch until it's stable.*

I have now switched to the `lite` branch.

And the error message is gone. (`/usr/lib/schildichat-desktop/resources/app/lib/i18n/strings/en_US.json` still does not exist, though. But in the meantime I also configured SchildiChat in the GUI, and one thing was to disable spell check.)

> *what does `git status` say in the schildichat-desktop directory?*

```
On branch makepkg
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   element-desktop (modified content, untracked content)

no changes added to commit (use "git add" and/or "git commit -a")
```

(I am bulding on Artix GNU/Linux using `makepkg`.)
