### ISSUE TITLE
Changelog for Latest Pre-Release

### ISSUE THREAD

**Issue by solonovamax** [SchildiChat/schildichat-desktop#267]
What features were dropped in the latest pre-release?
Could a changelog be provided?

**Comment by SpiritCroc** [comment]
Everything was dropped, except what's in [FEATURES.md](https://github.com/SchildiChat/schildichat-desktop/blob/lite/FEATURES.md).

**Comment by SpiritCroc** [comment]
Added link to FEATURES.md to the release.
