### ISSUE TITLE
[needs investigation] Search doesn't work

### ISSUE THREAD

**Issue by ShadowJonathan** [SchildiChat/schildichat-desktop#29]
Currently, search doesn't function properly, "matches" are found, but all rooms are shown regardless of input

**Comment by su-ex** [comment]
I assume you mean the room list search?
Or do you mean searching in a room?
Both works fine on my end.

**Comment by ShadowJonathan** [comment]
Room list search, it doesn't seem to function correctly

**Comment by su-ex** [comment]
Is it the same on https://app.schildi.chat or with Element flatpak?

**Comment by ShadowJonathan** [comment]
Element flatpak, 1.7.15

**Comment by su-ex** [comment]
So it doesn't work with Element flatpak **too**?

**Comment by ShadowJonathan** [comment]
Nope, like i said, i put in the search term and it says "x matches", and the X is the total amount of rooms im in, even when the search term is totally nonsensical

Edit: okay what the hell it works, same with the community thing, i guess they work after i restarted schildi somewhere along the way
