### ISSUE TITLE
Configurable room list element size (avatar and name with preview)

### ISSUE THREAD

**Issue by ShadowJonathan** [SchildiChat/schildichat-desktop#31]
Would be helpful if room-boxes could be scaled according to a slider, to be bigger or smaller according to preference.

A continuous slider is not possible with the upstream implementation right now.
So there are two options:
1. Find a better way to implement that
2. Stick to ~~5~~ 3 size options or so:
   - tiny: inline avatar + name
   - ~~small: slightly bigger avatar + name (maybe with preview in the same line and/or wrapping to a second)~~
   - medium: icon as big as name + single line preview (Element right now)
   - ~~big: medium with bigger icon~~
   - huge: SchildiChat right now (with two line preview)

And consider decorator size: https://matrix.to/#/!eSTlitQAfqxWWEHMFD:matrix.org/$orPaGuWZcFvyJKfcJ6lJyaPLmSO2fWQvL7xQt2PK86w

Check highest font size: https://matrix.to/#/!eSTlitQAfqxWWEHMFD:matrix.org/$Cfzf-Iycxiw2EayeQepRrPdQ6X50iSmVkdWrcuJuHQ0?via=supercable.onl&via=matrix.org&via=matrix.sp-codes.de

**Comment by su-ex** [comment]
Deferred until after spaces
