### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by michi7801** [SchildiChat/schildichat-desktop#42]
Hi everyone!

Is there a plan to support MacOS in the near future? I'm a Mac user myself and would love to help get this working, but unfortunately C is not the language I typically use, so editing the makefile myself is not really an option. Maybe I could help by providing the necessary platform?

**Comment by su-ex** [comment]
Indeed, the platform would be a first step, we're totally without one.
The easiest path might be to look what Element does and then try to recreate that.

**Comment by SpiritCroc** [comment]
FYI: while we have a Makefile in this repo, this does not have to do with C code here, but just allows us to type `make` without having to think about the right `yarn` command. If we're lucky, we just need to add two lines to the makefile and one line to `element-desktop/package.json` for the right electron-builder arguments ([I guess --mac](https://www.electron.build/cli)), but we haven't tried yet due to the lack of testing possibilities.

**Comment by su-ex** [comment]
I've built https://github.com/SchildiChat/schildichat-desktop/releases/download/v1.7.17-sc1/untested_SchildiChat-1.7.17-sc1-mac.tar.xz.
dmg and pkg won't work building on Linux due to signing.

**Comment by michi7801** [comment]
Thank you, I will try it out as soon as i finished working. Signing should not be necessary as long as you ignore the warning that pops up while opening the dmg.

**Comment by michi7801** [comment]
Currently the App fails with the following Error:

```
rocess:               SchildiChat [75459]
Path:                  /Applications/SchildiChat.app/Contents/MacOS/SchildiChat
Identifier:            chat.schildi.desktop
Version:               1.7.17-sc1 (1.7.17-sc1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           SchildiChat [75459]
User ID:               501

Date/Time:             2021-01-27 12:27:32.275 +0100
OS Version:            macOS 11.1 (20C69)
Report Version:        12
Anonymous UUID:        DB0F81CD-C36A-2CD7-4E51-1DCBBE33DF69

Sleep/Wake UUID:       EB3D38F0-49E2-4A9B-B521-6499F5F5CCB6

Time Awake Since Boot: 110000 seconds
Time Since Wake:       130 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 467A83CB-BA86-3F07-B652-B9256C74080A
Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/SchildiChat.app/Contents/MacOS/SchildiChat
  Reason: no suitable image found.  Did find:
	/Applications/SchildiChat.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/SchildiChat.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x1067ef000 -        0x106816fff +chat.schildi.desktop (1.7.17-sc1 - 1.7.17-sc1) <5CF444E6-280A-33A3-87FF-B56A6B4EC25C> /Applications/SchildiChat.app/Contents/MacOS/SchildiChat
       0x11409a000 -        0x114135fff  dyld (832.7.1) <DEA51514-B4E8-3368-979B-89D0F8397ABC> /usr/lib/dyld

Model: MacBookPro12,1, BootROM 186.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 2,7 GHz, 16 GB, SMC 2.28f7
Graphics: kHW_IntelIris6100Item, Intel Iris Graphics 6100, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464232333241314D412D4A442D460000
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464232333241314D412D4A442D460000
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1675.1)
Bluetooth: Version 8.0.2f9, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1
```

I am running the news Version of MacOS with the MacBook Pro 13 inch from 2015.

**Comment by su-ex** [comment]
Seems like Electron is missing/broken.
I have absolutely no clue what's wrong.

You could try to set up a build environment on your macOS PC:
1. Install required dependencies (don't know what they are named at Apple, you can orient on the required Debian packages)
2. Clone schildichat-desktop and check out the submodules
3. `cd element-desktop`
4. `yarn run build --mac dmg` (or pkg, tar.gz, tar.xz, ... instead of dmg, whatever works)

This doesn't require any makefiles.

**Comment by michi7801** [comment]
The biggest problems for me are the dependencies "libsqlcipher-dev" and "libsecret-1-dev". Everything else just works fine and the build evens runs as expected without those, but of course the resulting binary is not working. It just straight up doesn't open without any error at all.

**Comment by su-ex** [comment]
Sorry, I can't help you any further.
Maybe there are some build instructions for Element on macOS around, building SchildiChat should be similar to that.

**Comment by michi7801** [comment]
OK, seems like a good idea. I will post my results here if I am successful. Thank you anyway.

**Comment by michi7801** [comment]
So after tinkering for a while I got most errors sorted out, but one problem is still remaining. If I try to start the App through Terminal I get the following error:
```
Couldn't find webapp files in any of:
	/Users/michaelkaltenbrunner/Downloads/schildichat/schildichat-desktop/element-desktop/webapp.asar
	/Users/michaelkaltenbrunner/Downloads/schildichat/schildichat-desktop/webapp.asar
	/Users/michaelkaltenbrunner/Downloads/schildichat/schildichat-desktop/element-desktop/webapp
	/Users/michaelkaltenbrunner/Downloads/schildichat/schildichat-desktop/webapp
App setup failed: exiting Error: Failed to find webapp files
    at tryPaths (/Users/michaelkaltenbrunner/Downloads/schildichat/schildichat-desktop/element-desktop/src/electron-main.js:155:11)
    at async setupGlobals (/Users/michaelkaltenbrunner/Downloads/schildichat/schildichat-desktop/element-desktop/src/electron-main.js:161:16)
    at async App.<anonymous> (/Users/michaelkaltenbrunner/Downloads/schildichat/schildichat-desktop/element-desktop/src/electron-main.js:814:9)
error Command failed with exit code 1.
```

Did I do something wrong while preparing the app? Also when running the setup.sh I spotted this error:
```
Error moving new index into place: Error: ENOENT: no such file or directory, rename 'src/component-index.js.tmp' -> 'src/component-index.js'
```

Are these related with each other? Or do you have any other suggestions?

**Comment by su-ex** [comment]
It seems like the symlink of element-web/webapp into element-desktop is not in place: https://github.com/SchildiChat/schildichat-desktop/blob/a95770fb4958e0b72bff09ba9ecf2bf900eb476c/setup.sh#L28

To try if the webapp itself works, you can `cd element-web` and then `yarn start`. After that you should be able to open SchildiChat in a browser under http://localhost:8080 .

**Comment by michi7801** [comment]
Yes, after renaming the "config.sample.json" to "config.json" the Webapps indeed works. The unpackaged Electron App does not crash anymore after the command you suggested:
```
 ln -s ../element-web/webapp ./ || true 
```
Anyway the app still seems to not load correctly since the javascript console and the HTML-Tree of the electron are completely empty. Also, this only works with the unpackaged App when running with "yarn start". If I package the App it crashes like before.

**Comment by su-ex** [comment]
Please try in the schildichat-desktop folder:
1. `make clean`
2. `make desktop-common`
3. `yarn --cwd element-desktop run build --mac dmg`

**Comment by michi7801** [comment]
🎉 - The Electron now works fine. It looks like the "GPG" dependencies was missing and the command `yarnpkg --cwd element-desktop run fetch --cfgdir` failed for this reason.
After building it with `yarn --cwd element-desktop build`  it now works even in the packaged version. 

For me there are two things left:
- Fixing these two errors: `Keytar isn't installed; secure key storage is disabled.` and `Seshat isn't installed, event indexing is disabled.`
- Getting this to works constantly, so I can serve a script or at least a step by step instruction

**Comment by su-ex** [comment]
Great!
Did you run `build:native`? That's why I recommended you to run `make desktop-common`, see here: https://github.com/SchildiChat/schildichat-desktop/blob/a95770fb4958e0b72bff09ba9ecf2bf900eb476c/Makefile#L46

**Comment by michi7801** [comment]
Ok, so I got a semi reliable way to build it:
- `git clone --recurse-submodules https://github.com/SchildiChat/schildichat-desktop.git`
- `cd schildichat-desktop`
- `cp element-web/config.sample.json element-web/config.json`
- `yarn element-desktop add electron -D`
- `make desktop-common`
- `make clean`
- `make desktop-common`
- `yarn --cwd element-desktop run build`

I have to mention a few things here:
- First of all I installed the following dependencies with `brew`: 
  - `brew install rust node yarn gpg vim curl git make gcc g++ tcl`
  - I cannot say if this is all you need to build the app, because I am using brew since a long time and maybe there are some other dependencies I already had installed
- I do not know why, but `make desktop-common` fails till you - at least once - ran `make clean`. This is part of the error I get:
```
20% building 64/76 modules 12 active
/Users/User/Downloads/schildichat/schildichat-desktop/element-web/src/vector/platform/PWAPlatform.tsModuleNotFoundError: 
Module not found: Error: Can't resolve '../component-index' in '/Users/User/Downloads/schildichat/schildichat-desktop/element-web/src/vector'
```
- On the other hand `make clean` fails until I at least ran `make desktop-common` once. However sometimes I have to run it even two or three time. I get the following error:

```
yarn run v1.22.10
$ rimraf lib dist
/bin/sh: rimraf: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [clean] Error 127
```
- Last, but not least I am not quit sure if you have to copy the configuration but I did it anyway:
   - `cp element-web/config.sample.json element-web/config.json`

**Comment by su-ex** [comment]
Ok, try
```
make setup
make clean
make desktop-common
yarn --cwd element-desktop run build --mac dmg
```
please.

**Comment by michi7801** [comment]
I will adjust the config file.
The command `make setup` runs just fine, but the error generated by `make desktop-common` is still the same:
```
20% building 64/76 modules 12 active
/Users/User/Downloads/schildichat/schildichat-desktop/element-web/src/vector/platform/PWAPlatform.tsModuleNotFoundError: 
Module not found: Error: Can't resolve '../component-index' in '/Users/User/Downloads/schildichat/schildichat-desktop/element-web/src/vector'
```

**Comment by su-ex** [comment]
Hmm, could you try starting from scratch once again? And make sure the `yarn start` isn't running, that can sometimes interfere. Copying configs shouldn't be necessary as it's done by the make targets.

More _shouldn't™_ be necessary:
```
git clone --recurse-submodules https://github.com/SchildiChat/schildichat-desktop.git
cd schildichat-desktop
make desktop-common
yarn --cwd element-desktop run build --mac dmg
```

**Comment by su-ex** [comment]
Ohhhh, I think you might have run into this: https://github.com/vector-im/element-web/issues/15751#issuecomment-731247116

**Comment by michi7801** [comment]
Since MacOS is BSD based, this would perfectly make sense.

**Comment by michi7801** [comment]
Regarding your request to do a fresh download, I am doing this every time I try something new. 
The quick fix this person mentioned did not work for me. I updated the element-web's package.json just as he stated, but this doesn't do anything for me.

**Comment by su-ex** [comment]
Can you get a working macOS build?
There'll be a new release soon™ and it'd be great to add your macOS builds to the GitHub releases.

**Comment by michi7801** [comment]
Yes, I can get a working build, not with every try, but still. Actually I‘m using mine since a week and it works without a problem :)

The problem is that it is signed with my personal iCloud account, so I need like a Schildichat iCloud account or something.

**Comment by su-ex** [comment]
Great! 🙂
Feel free to do whatever necessary. 👍
I haven't updated schildichat-desktop yet, but if you pull the latest changes into all the submodules manually this will have the same effect.

**Comment by michi7801** [comment]
Yeah, the issue is that you need a telephone number to create a personal iCloud account or you pay like 100€ to create a developer account for proper signing. Neither of those is doable for me. I will try to build the app without signing, but I am not quiet sure how this affects the installation.

**Comment by su-ex** [comment]
Same issue like Windows then, costs for signing would be too high.
Staying unsigned is fine. 🤷

**Comment by michi7801** [comment]
Ok, so building the app again was like gambling. Yesterday I tried it like 2 hours and I were not able to build it at all. Today it compiled like first try and I have absolutely no clue why.

Anyway, I pulled the code for each submodule from its master branch and merged it manually (if needed). I tested the new build and it works fine. How can I provide you the file? It is 110MB big.

**Comment by su-ex** [comment]
Great! Did you use the `sc` branch for all the repos? `master` is not our main branch.
Can we reach you somewhere in private?

**Comment by michi7801** [comment]
Oh well, looks like i‘ll compile it again :‘D
I suppose that there is a matrix group too?

**Comment by su-ex** [comment]
> I suppose that there is a matrix group too?

Indeed: https://matrix.to/#/!eSTlitQAfqxWWEHMFD:matrix.org?via=supercable.onl&via=matrix.org&via=envs.net

**Comment by ShadowJonathan** [comment]
@michi7801 was this fixed?

**Comment by michi7801** [comment]
Quick summary for everyone reading this in the future:
- The fix was to call the `yarn reskindex` command in the matrix-react-sdk before doing `make desktop-common`
- There is a bundle for macOS in the new release
- I will update the README as soon as I can so everyone can build it.
