### ISSUE TITLE
AppImage and search of encrypted chats

### ISSUE THREAD

**Issue by benneti** [SchildiChat/schildichat-desktop#46]
Is it possible to enable search for encrypted chats in the appimage builds?
This would be really great, as these builds are the simplest way to get schildichat desktop on non Debian based linux distributions.

**Comment by su-ex** [comment]
Does it work with Element? Last time I checked there was an issue for Element about that.

**Comment by benneti** [comment]
The only semi useful bug report in element I saw was https://github.com/vector-im/element-web/issues/14229 and I don't think element has an official appimage (yet).
I think what might be worth a try that I try to get the deb up and running in a virtuel env and check wether it works there and if it does it should be a packaging problem of the appimage (I guess).

**Comment by benneti** [comment]
after some further investigation I think that the problem is that it cannot find libsqlcipher.so (even if it is existing in the virtual environment), do you think it is possible to add sqlcipher to the appimage (if it is not already)

**Comment by su-ex** [comment]
Indeed, a possible solution could be https://github.com/electron-userland/electron-builder/issues/2732#issuecomment-626299247.

**Comment by benneti** [comment]
It could be, is there a way to tell element/schildichat desktop to provide additional debugging information or write to a log file?

**Comment by su-ex** [comment]
Seems adding libsqlcipher isn't enough, I don't know what else could potentially be missing.

**Comment by benneti** [comment]
could it be libsecret?
But I think for this library it makes sense to rely on the system

**Comment by su-ex** [comment]
About debugging: Lunching from terminal and the devtools console is all I know about.
Link to AppImage with libsqlcipher: https://cloud.supercable.onl/s/5YEg2s558aEXQM7
For libsecret to rely on the system probably makes more sense indeed.

**Comment by benneti** [comment]
Ah ok thank you, it seems it was not the missing libsecret, also the appimage seems to not work with the devtools:
```
schildichat-desktop -- --devtools
Error: Cannot find module 'electron-devtools-installer'
Require stack:
- /nix/store/ihqz08m7mc134r2p2i56427lkzhcizj1-schildichat-desktop-1.7.20-sc1-extracted/resources/app.asar/src/electron-main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:921)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at App.<anonymous> (/nix/store/ihqz08m7mc134r2p2i56427lkzhcizj1-schildichat-desktop-1.7.20-sc1-extracted/resources/app.asar/src/electron-main.js:827:80) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/ihqz08m7mc134r2p2i56427lkzhcizj1-schildichat-desktop-1.7.20-sc1-extracted/resources/app.asar/src/electron-main.js',
    undefined
  ]
}
No update_base_url is defined: auto update is disabled
```

**Comment by su-ex** [comment]
I meant launching through `./SchildiChat....AppImage`.
devtools from electron (Chromium) once it's open I meant (Ctrl+Shift+I or soemthing like that).

**Comment by benneti** [comment]
Ok this confirms the problem:

```
EventIndex: Error initializing the event index 
Object
message: "Error opening the database: SqlCipherError("Sqlcipher support is missing")"
__proto__: Object
```

**Comment by su-ex** [comment]
Can you check libsqlcipher is included (in the issue post I linked above at the end)?

**Comment by benneti** [comment]
it is there 
```
appimagetool -l SchildiChat-1.7.21-sc1.AppImage | grep libsqlcipher                                                                     appimagekit
appimagetool, continuous build (commit ), build <local dev build> built on 2021-02-06 18:22:40 UTC
usr/lib/libsqlcipher.so.0
```

**Comment by su-ex** [comment]
Then I have absolutely no clue what's missing.

**Comment by benneti** [comment]
Me neither

**Comment by su-ex** [comment]
Maybe a naming or path issue. 🤔
However I don't know how to find out where it looks for that library.

**Comment by su-ex** [comment]
Did you try clearing cache and maybe logout/login?

**Comment by benneti** [comment]
where does the deb expect the libraries maybe I can get this one to work in nixos :sweat_smile: ?

**Comment by su-ex** [comment]
/usr/lib/x86_64-linux-gnu/libsqlcipher.so.0

**Comment by benneti** [comment]
I'll try to emulate this in my environment then.
Also could this at all be related to this:
DEPRECATED CONFIG OPTION: In the future, default_server_name will not be accepted. Please use default_server_config instead.
e.<computed> @ init.js:1

**Comment by su-ex** [comment]
I don't think this is related.

**Comment by benneti** [comment]
Starting from
```
schildichat-desktop                     
Seshat unexpected error: Error: libsqlcipher.so.0: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/nix/store/r6600gbyx4s946kfws08xl413n2g2d5f-schildichat-desktop-1.7.20-sc1/share/schildichat-desktop/resources/app.asar/node_modules/matrix-seshat/lib/index.js:15:16)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
No update_base_url is defined: auto update is disabled
^C%                                 
```
I can get to 
```
schildichat-desktop                     
No update_base_url is defined: auto update is disabled
```
but search still does not work even after completely purging my local configuration.

So it might after all not be related to the missing library per se, maybe its a version mismatch I don't know.

**Comment by su-ex** [comment]
Is this still an issue? It seems it might work (now).
See here and subsequent messages: https://matrix.to/#/!eSTlitQAfqxWWEHMFD:matrix.org/$uqDJfF_yOHPgqGxOd7kMTicVW_Dx5CXrDRyFxrE4guI?via=supercable.onl&via=matrix.org&via=envs.net

**Comment by benneti** [comment]
sorry for the late reply, I don't use the appimage anymore. So if someone has it working I think this can definitely be closed. 
Also if it still matters I think by now this was the problem: https://github.com/sqlcipher/sqlcipher/issues/385 i.e. that SQLite was loaded instead of SQLCipher .

**Comment by su-ex** [comment]
This may be, this hit me a few times already.
