### ISSUE TITLE
RTL better support

### ISSUE THREAD

**Issue by HKalbasi** [SchildiChat/schildichat-desktop#52]
This issue is for tracking UI problems for right to left languages. I will fill it incrementally.

- [x] For start, Username should be near avatar regardless of language direction:
![image](https://user-images.githubusercontent.com/45197576/109871583-94db7300-7c80-11eb-83da-43b890447c83.png)

- [x] And if sender's username is in ltr but message text is in rtl, can lead to wrong direction: (Can solve by separating sender name and message text into two elements, maybe hard to solve)
![image](https://user-images.githubusercontent.com/45197576/109874749-c3f3e380-7c84-11eb-924b-1933c2de535a.png)
In this image, image room name is correct but last message (which is equal to room name) is reversed.

And some good links (maybe useless, maybe you already aware of):
* [unicode-bidi property in css](https://developer.mozilla.org/en-US/docs/Web/CSS/unicode-bidi)
* [unicode-bidi resolve algorithm](https://www.unicode.org/reports/tr9/)

**Comment by su-ex** [comment]
Thanks! 👍
I've added checkboxes so they can be ticked off. ☑️

**Comment by su-ex** [comment]
If the username is left aligned, what should happen to the text below? Should the actual text be left aligned too or right aligned?

**Comment by HKalbasi** [comment]
I think it is not so important because bubble size is determined via text size and always it fill the bubble. In telegram, username is left aligned but text is right aligned, and that's good.

Also I recently found a way to fix number 2, by adding a U+2068 charachter (isolation character) between sender name and message text. https://github.com/tulir/mautrix-telegram/issues/592

**Comment by su-ex** [comment]
I think I got them.
Please check after the next release if these problems are gone and just continuously update the list and maybe close while there is nothing and reopen once there something pops up again.

**Comment by HKalbasi** [comment]
Thank you for your great work!

**Comment by HKalbasi** [comment]
Recently I upgraded my browser. It is brave based on chromium 90. After upgrade, rtl become completely broken everywhere (in messages, sending messages, etc). It is still correct in firefox. This is probably problem with chromium but I'm not sure because my other PWAs are ok.

**Comment by su-ex** [comment]
Does it work with Chromium 90?
How does Element (if it's about anything except the bubble layout) or the from Element inherited "modern" layout (if it's about the room view) behave?
Screenshots (how it is vs how it should be) and maybe even offending classes of elements (devtools) would be great!

**Comment by HKalbasi** [comment]
Brave (wrong):
![image](https://user-images.githubusercontent.com/45197576/115968684-45157b80-a54e-11eb-9c51-e3b27f55d03b.png)

Firefox (correct):
![image](https://user-images.githubusercontent.com/45197576/115968712-6d04df00-a54e-11eb-9d57-5545807ca670.png)

It has `dir="auto"` and definitely should work!

**Comment by su-ex** [comment]
Hmm, very weird. I think I can't reproduce this with Chromium 90. Maybe I'll install Brave later to test there.
Does Element's text input field behave right?

**Comment by HKalbasi** [comment]
Yes it seems brave-specific. Anyway it is related to chrome or brave and does nothing to do with schildi. So I will close this issue.

**Comment by su-ex** [comment]
I use [`:dir()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:dir) for enhanced displaying of rtl. Since there's much user produced content where the direction is not known this was the only feasable way without messing around with JavaScript. For Chromium this is [in development](https://www.chromestatus.com/feature/5751531651465216) and according to the [tracking bug](https://code.google.com/p/chromium/issues/detail?id=576815) there's slow but steady progress.
**However, this is only used for cosmetics**: With Chromium right now rtl text might be left aligned and such, but the word order should be right. Since the desktop electron builds are based upon Chromium I definitely tested that and the word order matched Firefox, although it might not be pretty until this is implemented there too.

**Comment by HKalbasi** [comment]
No this is not related to `:dir()` and it is ok in chromium 90 (and was ok in brave) and I can replicate it in https://hkalbasi.github.io/notes/test-rtl/ without any css or js.

**Comment by HKalbasi** [comment]
In the latest release direction is always LTR in message bubbles:

![image](https://user-images.githubusercontent.com/45197576/155976210-7135b21a-1db7-495b-ae6d-c1322921230b.png)

But it is fine in rooms list and message editor:

![image](https://user-images.githubusercontent.com/45197576/155976478-180d0e4c-27b5-49d8-9f30-0782b5c50a3f.png)
![image](https://user-images.githubusercontent.com/45197576/155976539-c071d6b2-d788-4242-a420-46b501879fa1.png)
