### ISSUE TITLE
how compile to windows

### ISSUE THREAD

**Issue by AnonymousWebHacker** [SchildiChat/schildichat-desktop#53]
I would like a wiki or guide on how to compile for windows, thank you very much

**Comment by su-ex** [comment]
Would be nice indeed, but till now I've only been building for Windows on Linux. Thus I'm not sure what the required steps are to build for Windows on Windows. Building for Windows on Linux should be simple and the steps are shown in the readme.

**Comment by SpiritCroc** [comment]
I did try to get a working building setup on Windows initially, but did not finish it since the I ran out of storage in my VM, and noticed building for Windows also works on Linux.
Here are the (unconfirmed) steps that I wrote down while doing so, that might hint you in the right direction:

## Build setup

- Install git.
- Install nodejs.
- Install python and add it to PATH in Git Bash.
- Install visual studio command line tools, including c++ support, for nmake and rust.
- Install yarn, e.g. with `npm install -g yarn`.
- Use Git Bash to do the initial setup steps and further steps.

## Compile

Use `make`, if you can install that on Windows (untested), or just run the Makefile commands for web and desktop manually.

**Comment by AnonymousWebHacker** [comment]
I was asking to compile from linux, but it's true, it's in the readme, I just don't understand, let me see it calmly.
One question, is the visual studio necessary for something? or are you just referring to a normal text editor?

Thank you very much to abos for your quick response :)

**Comment by AnonymousWebHacker** [comment]
I was asking to compile from linux, but it's true, it's in the readme, I just don't understand, let me see it calmly.
One question, is the visual studio necessary for something? or are you just referring to a normal text editor?

Thank you very much to abos for your quick response :)

**Comment by AnonymousWebHacker** [comment]
When I try to compile, I'll tell you how it went, and close the issue

**Comment by AnonymousWebHacker** [comment]
When I try to compile, I'll tell you how it went, and close the issue

**Comment by AnonymousWebHacker** [comment]
So? 
1 - Dependences
`vim curl git make gcc g++ libsqlcipher-dev pkg-config libsecret-1-dev bsdtar curl nodejs>v14.x yarn`

2-
 curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
$ echo 'export PATH="$PATH:$HOME/.cargo/bin"' >> .bashrc
$ source .bashrc

3-
git clone repo
cd repo, nano conf.json and
make windows-setup && make debian
 
 only that?

**Comment by su-ex** [comment]
Almost.

1. If you're on Debian, just run these for the dependencies: https://github.com/SchildiChat/schildichat-desktop#debian-build-dependencies (if you're on another distro, you need to figure out what you need, they might be named different or not exist as package)
2. Initial setup: https://github.com/SchildiChat/schildichat-desktop#initial-setup
3. If you want a custom config, better copy the config.json from configs/sc to configs/your-config and adjust it only there.
4. Then (with 3.) you can call CFGDIR="configs/your-config" make

**Comment by su-ex** [comment]
_accidentally hit close_

**Comment by SpiritCroc** [comment]
> One question, is the visual studio necessary for something? or are you just referring to a normal text editor?

The "visual studio command line tools" allow you to install nmake and rust on Windows by installing the c++ support package. They are not required if you can get the required tools from somewhere else. On Linux, it's easier to get all required dependencies directly.

**Comment by AnonymousWebHacker** [comment]
Thank you both for your quick response and for helping me. I hope you keep improving this fork, I hope to give you sujestions

**Comment by su-ex** [comment]
Did you get it working? Any concrete suggestions on how to improve the readme? Otherwise please close this so it doesn't get stale.
