### ISSUE TITLE
Building Desktop error

### ISSUE THREAD

**Issue by AnonymousWebHacker** [SchildiChat/schildichat-desktop#55]
yarn : v1.22.10
nodejs: v14.16.0

make windows-setup-releaase

}
neon ERR! spawn cargo ENOENT

Error: spawn cargo ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Makefile:52: recipe for target 'desktop-common' failed
make: *** [desktop-common] Error 1
root@compiler:/opt/nodex/schildichat-desktop# 

=====================================================
neon ERR! Command failed: cargo metadata --format-version=1 --no-deps
error: no override and no default toolchain set

Error: Command failed: cargo metadata --format-version=1 --no-deps
error: no override and no default toolchain set

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Makefile:52: recipe for target 'desktop-common' failed
make: *** [desktop-common] Error 1

**Comment by su-ex** [comment]
Cargo is missing (see last section of Debian installation dependencies)

**Comment by su-ex** [comment]
Feel free to reopen if this is not resolved.

**Comment by AnonymousWebHacker** [comment]
@su-ex I have had problems with the compilation, I have not succeeded yet, that is why I had not closed it. Thanks for the help

**Comment by su-ex** [comment]
If you have further questions of this sort this is better to be discussed in our [room on Matrix](https://matrix.to/#/#schildichat-web:matrix.org).
