### ISSUE TITLE
Swipe to reply [Feature Request]

### ISSUE THREAD

**Issue by araccaine** [SchildiChat/schildichat-desktop#58]
**Current behavior:**
To reply on a specific message you have to long press on it.

**Possible enhancement:**
To reply just swipe right to on the message (like in other messaging apps)

**Comment by su-ex** [comment]
Do you really mean the Web/Desktop version?
What makes me doubt that is relying on web/desktop works via the hover box

**Comment by su-ex** [comment]
_damn, I hate that "Close with comment" button on GitHub mobile_

**Comment by araccaine** [comment]
> Do you really mean the Web/Desktop version and not Android?

Yeah... I am slightly dumb, sorry. I meant the Android Version. Should I reopen an issue there?

**Comment by SpiritCroc** [comment]
> > Do you really mean the Web/Desktop version and not Android?
> 
> Yeah... I am slightly dumb, sorry. I meant the Android Version. Should I reopen an issue there?

Just go to settings / labs / Enable swipe to reply in timeline
