### ISSUE TITLE
Allow Adding Comments to Files and Images during Upload

### ISSUE THREAD

**Issue by AnonymousWebHacker** [SchildiChat/schildichat-desktop#59]
What if after a File or Image, you could add a comment, just like Telegram does, which lets you comment on the uploaded photo

**Comment by su-ex** [comment]
That's dependent on the protocol and would only make sense if it has farther client support anyway. 
The `body` of the `m.image` doesn't seem to be intended for a comment but rather an alternative text if the image can not be shown or simply the filename: https://matrix.org/docs/spec/client_server/latest#id339
So this is nothing that can be solved by SchildiChat alone and is far better suited for upstream.

**Comment by su-ex** [comment]
This is in the roadmap for upstream thus I will close this here.
