### ISSUE TITLE
Upstream changes

### ISSUE THREAD

**Issue by Leon0402** [SchildiChat/schildichat-desktop#6]
Hi, 

would you consider upstreaming features? I do especially have chat bubbles in mind. It's a long open issue: https://github.com/vector-im/element-web/issues/4635 

Thanks! :)

**Comment by SpiritCroc** [comment]
If the Element team is interested in it, I'm open to it. I'm not sure how their design process works, though.

The current implementation is not ready for this, as there are some layout bugs remaining, and the bubbles are hardcoded instead of providing a proper setting at the moment.

**Comment by Leon0402** [comment]
I'm not sure either, it's just something very high on my personal wishlist for element and it would be great if it could made it way into element. I believe a lot of people would prefer not to have, so it would need to be configurable and perhaps off by default (you can then enable it here by default).

**Comment by su-ex** [comment]
Upstreaming the bubble layout is ongoing.
I already have and on occasion also will do pull requests for some other fixes/features.
