### ISSUE TITLE
The bubbles don't seem to display well.

### ISSUE THREAD

**Issue by caywin25** [SchildiChat/schildichat-desktop#62]
![chat](https://user-images.githubusercontent.com/55273439/114301507-c849c280-9ab4-11eb-87ea-59a78248674b.png)
Hello and thank you for your work
When I want to use the bubbles, they don't seem to display well or as if no style was taken into account. (image attached)

Is this normal?
Is there a block somewhere?
Thanks

**Comment by su-ex** [comment]
That's very little information. What browser? What OS?
And as far as I can see there are bubbles, just some weird lines across each.
If it's a environment I can set up myself I can test, otherwise it'd be helpful to find out about this with the browser's devtools.

**Comment by caywin25** [comment]
Ah yes my bad.
Browser : firefox
OS : Arch Linux.
But with dev tools, I can see problem with : CORS missing allow origin.

Can the problem come from there?
Thanks

**Comment by su-ex** [comment]
That's actually my normal test setup so it should have appeared to me too.
If the layout is loaded to the extent it is I highly doubt it's related to CORS, that'd rather be a no design at all or everything I think.
Do you self host? Does it happen on https://app.schildi.chat (too)?
If it does happen there too, please try to hit Ctrl+Shift+C and then select with your mouse pointer the element causing the weird lines. This way it might be possible to find out what's causing this.

Or do you use some sort of dark theme extension or a custom theme? The colors from your screenshot look slightly different compared to those when I put my instance next to it.

**Comment by caywin25** [comment]
Ah yes my bad sorry :(
It was my addon dark reader.

I'm sorry :(
Issue solved 
Thank you very much
