### ISSUE TITLE
Misleading message when the computer is offline

### ISSUE THREAD

**Issue by probonopd** [SchildiChat/schildichat-desktop#70]
Please do not assume that computers are connected to the internet all the time.

Nothing is "misconfigured" here. The machine just isn't online.

![image](https://user-images.githubusercontent.com/2480569/120936997-399b9f80-c70b-11eb-87c3-773e4b73020e.png)

**Comment by su-ex** [comment]
Is this about the client being offline or the server being offline? I think I never actually saw that screen.

Anyway, I highly doubt this is specific to SchildiChat because there's nothing changed in that regard compared to Element. So this issue is far better suited for upstream.

**Comment by probonopd** [comment]
Well, on our test server we run apps under test in a bubblewrap sandbox that disallows all network traffic.

**Comment by su-ex** [comment]
I agree this message is misleading. However, I probably won't target that and leave this to upstream.

**Comment by probonopd** [comment]
Looks like the message is coming from http://matrix-org.github.io/matrix-js-sdk/9.8.0-rc.1/autodiscovery.js.html.
So shall we open a ticket at https://github.com/matrix-org/matrix-js-sdk/issues?

**Comment by su-ex** [comment]
Yes, probably.
Otherwise https://github.com/vector-im/element-web/issues, they'll probably arrange it in a way that suits them.
And of course check before that the same is happening with Element, but I highly doubt it is not.
