### ISSUE TITLE
The windows version is way to Loud

### ISSUE THREAD

**Issue by marvin1099** [SchildiChat/schildichat-desktop#71]
The Windows Version on my PC is way too loud.
I can turn it down but it resets with every restart.
This means that after every restart the calls come in to my ears way to loud.
Any ideas on what I should do.
Maybe there is a switch/argument for that when starting up SchildiChat.
I tried nircmd but I can't check if it was successful or if the  schildichat output was already created so I have to repeat the command forever.
This creates a constant loading bar so a not so nice solution.
I can of course manually stop the script after I started a call. But there has to be a better solution.

**Comment by su-ex** [comment]
Does the same happen with Element?
I've never touched anything regarding voip to my knowledge.
Thusthis issue should be fixed upstream with Element.

**Comment by su-ex** [comment]
I don't understand this issue and it's likely something SchildiChat won't target anyway. Thus I'm closing this. Feel free to reopen this issue with more information on how to reproduce this if it's a SchildiChat related bug which can't be reproduced with Element.
