### ISSUE TITLE
fix width list of chats

### ISSUE THREAD

**Issue by lagemeet** [SchildiChat/schildichat-desktop#74]
![image](https://user-images.githubusercontent.com/80648740/122994988-aa9cb180-d3b1-11eb-86b7-f97377bb2203.png)

**Comment by su-ex** [comment]
I'm trying to reproduce this, but I can't.
When du you run into this?

**Comment by su-ex** [comment]
Since this didn't occur to anybody else till now, I'm closing this. If this still happens to you, feel free to reopen this issue with more information on how to reproduce this.
