### ISSUE TITLE
Spaces Don't Work

### ISSUE THREAD

**Issue by 23marabi** [SchildiChat/schildichat-desktop#75]
When I join a space on SchildiChat android or web, it shows up and works properly, how it's supposed to. But when I go to schildichat-desktop on linux the spaces that I joined don't show up. I have spaces enabled in all of them. When someone invites me to a space, again it works properly on android/web, but on desktop it just shows an invite to a normal room. I am able to create a space on desktop though, although when I invite people to it to them it just shows up as a room invite even when spaces work normally for them. And when I go back to the android/web versions, the space I created doesn't show up. I've tried reloading the apps, updating, turning spaces on and off again, no luck.

I'm on arch linux, using SchildiChat version `1.7.24-sc1`

**Comment by su-ex** [comment]
Please upgrade to the latest version.

**Comment by 23marabi** [comment]
Ah, sorry about that. For some reason my system update didn't update schildichat for some reason. It seems to work properly now.
