### ISSUE TITLE
hygrogen element web

### ISSUE THREAD

**Issue by caywin25** [SchildiChat/schildichat-desktop#77]
Hello, 

A new element projet web is born named : hydrogen
>> https://github.com/vector-im/hydrogen-web

This project is more lightweigth than element-web.
Do you think for this project for schildichat-web ?

Thank you very much for your work.

**Comment by su-ex** [comment]
I'm very much aware of Hydrogen, but it's current development speed is still quite high and therefore things are volatile which would possibly make custom changes break quite often. I deem it too early to look into more deeply, but I might make some simpler changes like color adjustments and replace the chat layout with a bubbly one which I actually wanted to do for some time already.
