### ISSUE TITLE
Media loading anew each time entering a room and making the timeline jump

### ISSUE THREAD

**Issue by ghostlyentity** [SchildiChat/schildichat-desktop#93]
greetings, i have noticed a change in the newest version

Situation:
when i view a channel is now always reloads all pictures, causing me to sometimes jump up the channel (happens in unencrypted channels, i stay at the bottom it seems in encrypted channels) 

Expected result:
like previous version, do not reload all pictures and stay at the bottom of the selected channel

Actual result:
reloads all media in a channel, sometimes causing me to jump to random points in the channel, reloads happens every time, jumping happens most of the time

OS: EndeavourOS
Kernel: 5.14.2-arch1-2
schildi.chat version: v1.8.4-sc1

i apologize if this is not enough info, i will hopefully be able to provide whatever additional info is needed

**Comment by su-ex** [comment]
Right, this is a nuisance. I'm wondering if Element does this as well now. I'll try to find out when this actually started and fix it.

**Comment by ghostlyentity** [comment]
on matrix as far as i can tell, it either doesnt happen or its too fast to notice

**Comment by ghostlyentity** [comment]
i would like to add, in the web version it does seem to jump to the bottom while media reloads

**Comment by su-ex** [comment]
I'm not sure if I can follow you. Could you maybe take a video?

**Comment by su-ex** [comment]
And can you please check if the issue is maybe already gone here: gttps://schildidbg.supercable.onl

**Comment by ghostlyentity** [comment]
as the changes titles, the desktop client still jumps to random points in the timeline as messages (and media) loads in
but in the web version it does jump to the bottom or sometimes stays there as messages reload

**Comment by su-ex** [comment]
So is the behaviour of the version I linked different compared to that before?
Still, I can't quite follow you.
I've stimulated a slow connection and actually it seems fine, although while jumping around in the timeline.

**Comment by ghostlyentity** [comment]
apologies, i forgot to test
but it does seem to behave differently, i dont see it reloading anything
similar to how schildichat seems to have done a few versions ago

**Comment by su-ex** [comment]
Great, then it got probably fixed and will hopefully be fine again in the next release.

**Comment by su-ex** [comment]
Should hopefully be fixed with the latest version v1.8.5-sc1 now. Please reopen if this issue persists.

**Comment by ghostlyentity** [comment]
im sorry to say that its still present. (checked both aur and flatpak and appimage)
in certain channels with a lot of media i even have the problem that when i click the "go to the bottom" arrow it jumps back up to where it was before instantly.
web version works perfectly fine.
another (im not sure what to call it honestly) thing that i have seen for a few version that sometimes even when i am at the bottom of a channel, the arrow to go down stays present, no amount of scrolling or clicking it will make it go away (restarting sometimes does) text only channels do seem to work perfectly.

but i also like to thank you again for your hard work.

**Comment by su-ex** [comment]
Could you try the web version with both Firefox and Chromium to see if the browser makes a difference?
And can you take a video, please? I'm still not sure what this is actually about and I can't reproduce it.

**Comment by ghostlyentity** [comment]
the web versions work perfectly fine (tried FF, vivaldi and gnome web)
i was unable to capture the problem of jumping back and forth in the timeline, but i was able to capture the other problem, said problem also makes it so when a new message appears my windows stays in the timeline where it was instead of jumping back down.
as previously said, this seems to only be a problem with channels with a lot of media in them, text channels are rarely if at all affected.
i apologize for not providing good enough evidence and explanation

https://user-images.githubusercontent.com/86599520/134334900-30488a0e-55c9-444d-b854-78e873c9861e.mp4

.

**Comment by su-ex** [comment]
The video seems broken, I can't play it. I'm still not sure what this issue is about.

**Comment by ghostlyentity** [comment]
The video plays perfectly in chromium based browsers, i thought it was something wrong with my setup that didnt play it in librewolf.
Apologies but i dont think i can give any more accurate information than i already have.

**Comment by su-ex** [comment]
It's broken for me in Chromium as well. 🤔

**Comment by su-ex** [comment]
Your second issue ... is a second issue. xD
I've opened it here: https://github.com/SchildiChat/schildichat-desktop/issues/112
This is together with https://github.com/SchildiChat/schildichat-desktop/issues/96 in my priority list for the sake of parity with Android.

**Comment by su-ex** [comment]
Is this still an issue?

**Comment by su-ex** [comment]
Images are indeed loading anew each time changing into a room, but this is with upstream Element as well.
It's true as well that the timeline is jumpy if media loads somewhere in between, but that has always been like that to my knowledge and this is something really hard to counteract.

The reloading each time is definitely an upstream introduced issue.
The jumpiness when scrolling around in a room is there with upstream as well.
So yes, this issue is still around. However, due to its complexity and it being existent on upstream as well this is something which should be fixed upstream (I'll probably not tackle this due to lack of time).

**Comment by su-ex** [comment]
Note to self: Link previews seem to make the timeline jump, even more so than images and other media.
