### ISSUE TITLE
Error M_UNKNOWN

### ISSUE THREAD

**Issue by NovaMoon** [SchildiChat/schildichat-desktop#94]
I tried to join this chat today. 
`#streamlink_streamlink-twitch-gui:gitter.im#`

and i simply get this error message 

`#streamlink_streamlink-twitch-gui:gitter.im# is not accessible at this time.
Try again later, or ask a room admin to check if you have access.
M_UNKNOWN was returned while trying to access the room. If you think you're seeing this message in error, please submit a bug report.`

i followed the invite link from here [Invite](https://matrix.to/#/#streamlink_streamlink-twitch-gui:gitter.im#/#streamlink_streamlink-twitch-gui:gitter.im) and tried to manually join through discovery with the same result.

**Comment by su-ex** [comment]
Probably not a client issue. Maybe try later again, with another alias or the id.

**Comment by su-ex** [comment]
Oh, it seems your invite link is invalid, try this instead: https://matrix.to/#/#streamlink_streamlink-twitch-gui:gitter.im

**Comment by NovaMoon** [comment]
ah that invite link works. sorry im new to matrix and wasnt sure if its a bug in the client or something else. solved
